// Code generated by tools/eventgen; DO NOT EDIT.
// Source: schemas/event.v1.json event_types

package event

// EventTypeSpecGenerated mirrors the schema event_types metadata block.
type EventTypeSpecGenerated struct {
	Type           string   `json:"type"`
	Description    string   `json:"description"`
	Profiles       []string `json:"profiles"`
	Criticality    string   `json:"criticality"`
	RequiredFields []string `json:"required_fields"`
}

// EventTypesGenerated is generated from schemas/event.v1.json event_types.
var EventTypesGenerated = []EventTypeSpecGenerated{
	{Type: TypeBundleManifest, Description: "Bundle manifest (seq 0, always first in a new bundle)", Profiles: []string{"atb.profile.privileged_tool_action", "atb.profile.rag_answer", "atb.profile.data_export", "atb.profile.policy_decision", "atb.profile.human_override", "atb.profile.background_automation"}, Criticality: "critical", RequiredFields: []string{"version", "created_at", "bundle_id"}},
	{Type: TypeBundleAnchor, Description: "RFC 3161 TSA timestamp anchor", Profiles: []string{"all"}, Criticality: "required", RequiredFields: []string{"tsa_url", "bundle_hash", "tsr_hash", "tsr_der", "certified_time"}},
	{Type: TypeBundleSignature, Description: "Ed25519 bundle signature", Profiles: []string{"all"}, Criticality: "required", RequiredFields: []string{"bundle_hash", "signature", "pubkey"}},
	{Type: TypeSnapshot, Description: "Bundle snapshot marker", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{"name", "bundle_hash", "record_count", "snapshot_at"}},
	{Type: TypeBundlePushed, Description: "Bundle pushed to remote WORM target (atb push)", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{}},
	{Type: TypeAIRequestReceived, Description: "AI request received at app boundary", Profiles: []string{"atb.profile.rag_answer", "atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.policy_decision", "atb.profile.human_override"}, Criticality: "critical", RequiredFields: []string{"request_id", "actor_id_hash", "purpose_tag"}},
	{Type: TypeAIResponseSent, Description: "AI response sent from app boundary", Profiles: []string{"atb.profile.rag_answer"}, Criticality: "required", RequiredFields: []string{"request_id", "output_digest"}},
	{Type: TypeAILLMCall, Description: "Canonical LLM lifecycle event for integrations", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{}},
	{Type: TypeAIToolExec, Description: "Canonical tool execution lifecycle event for integrations", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{}},
	{Type: TypeAIChainRun, Description: "Canonical chain or step lifecycle event for integrations", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{}},
	{Type: TypeAIPolicyDecision, Description: "Policy engine decision (allow/deny)", Profiles: []string{"atb.profile.privileged_tool_action", "atb.profile.rag_answer", "atb.profile.data_export", "atb.profile.policy_decision"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeAIRetrievalExecuted, Description: "Retrieval step executed (RAG)", Profiles: []string{"atb.profile.rag_answer"}, Criticality: "required", RequiredFields: []string{}},
	{Type: TypeAIModelInvoked, Description: "LLM invocation sent", Profiles: []string{"atb.profile.rag_answer"}, Criticality: "critical", RequiredFields: []string{"model_provider", "model_id", "model_parameters_digest", "prompt_digest"}},
	{Type: TypeAIModelOutput, Description: "LLM output received", Profiles: []string{"atb.profile.rag_answer"}, Criticality: "critical", RequiredFields: []string{"output_digest", "output_format"}},
	{Type: TypeAIActionPrecommit, Description: "Pre-commit record for a gated privileged action", Profiles: []string{"atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.policy_decision", "atb.profile.human_override"}, Criticality: "critical", RequiredFields: []string{"action_id", "action_type", "action_parameters_digest", "target_resource_id", "intended_effect"}},
	{Type: TypeAIActionExecuted, Description: "Privileged action executed through gate", Profiles: []string{"atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.human_override"}, Criticality: "critical", RequiredFields: []string{"action_id", "execution_outcome", "tool_receipt_digest"}},
	{Type: TypeAIActionCommitted, Description: "Privileged action committed to sink", Profiles: []string{"atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.human_override"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeAIHumanApproval, Description: "Human approval of an action or override", Profiles: []string{"atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.human_override"}, Criticality: "required", RequiredFields: []string{}},
	{Type: TypeAIOverrideRequested, Description: "Human override requested", Profiles: []string{}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeAIJobScheduled, Description: "Background job scheduled", Profiles: []string{"atb.profile.background_automation"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeAIJobStarted, Description: "Background job started by worker", Profiles: []string{"atb.profile.background_automation"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeAIJobStep, Description: "Individual step within a background job", Profiles: []string{"atb.profile.background_automation"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeAIJobCompleted, Description: "Background job completed", Profiles: []string{"atb.profile.background_automation"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeDataExportPrecommit, Description: "Pre-commit record for a data export", Profiles: []string{"atb.profile.data_export"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeDataExportExecuted, Description: "Data export executed to sink", Profiles: []string{"atb.profile.data_export"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeDevSession, Description: "Developer session marker (tooling use)", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{}},
	{Type: TypeSnapshotBuild, Description: "Build snapshot (tooling use)", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{}},
	{Type: TypeCorroborationExternal, Description: "External corroboration record (adapter-retrieved evidence)", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{}},
	{Type: TypeRAGIndex, Description: "PageIndex document tree build record (index_hash, node_count)", Profiles: []string{"atb.profile.rag_answer"}, Criticality: "required", RequiredFields: []string{}},
	{Type: TypeRAGRetrieval, Description: "PageIndex reasoning-based retrieval result (node_id, page_start/end)", Profiles: []string{"atb.profile.rag_answer"}, Criticality: "required", RequiredFields: []string{}},
}

// RegistryGenerated is the EventInfo view generated from schemas/event.v1.json event_types.
var RegistryGenerated = []EventInfo{
	{TypeBundleManifest, "Bundle manifest (seq 0, always first in a new bundle)", "atb.profile.privileged_tool_action,atb.profile.rag_answer,atb.profile.data_export,atb.profile.policy_decision,atb.profile.human_override,atb.profile.background_automation", "critical"},
	{TypeBundleAnchor, "RFC 3161 TSA timestamp anchor", "all", "required"},
	{TypeBundleSignature, "Ed25519 bundle signature", "all", "required"},
	{TypeSnapshot, "Bundle snapshot marker", "", "informational"},
	{TypeBundlePushed, "Bundle pushed to remote WORM target (atb push)", "", "informational"},
	{TypeAIRequestReceived, "AI request received at app boundary", "atb.profile.rag_answer,atb.profile.privileged_tool_action,atb.profile.data_export,atb.profile.policy_decision,atb.profile.human_override", "critical"},
	{TypeAIResponseSent, "AI response sent from app boundary", "atb.profile.rag_answer", "required"},
	{TypeAILLMCall, "Canonical LLM lifecycle event for integrations", "", "informational"},
	{TypeAIToolExec, "Canonical tool execution lifecycle event for integrations", "", "informational"},
	{TypeAIChainRun, "Canonical chain or step lifecycle event for integrations", "", "informational"},
	{TypeAIPolicyDecision, "Policy engine decision (allow/deny)", "atb.profile.privileged_tool_action,atb.profile.rag_answer,atb.profile.data_export,atb.profile.policy_decision", "critical"},
	{TypeAIRetrievalExecuted, "Retrieval step executed (RAG)", "atb.profile.rag_answer", "required"},
	{TypeAIModelInvoked, "LLM invocation sent", "atb.profile.rag_answer", "critical"},
	{TypeAIModelOutput, "LLM output received", "atb.profile.rag_answer", "critical"},
	{TypeAIActionPrecommit, "Pre-commit record for a gated privileged action", "atb.profile.privileged_tool_action,atb.profile.data_export,atb.profile.policy_decision,atb.profile.human_override", "critical"},
	{TypeAIActionExecuted, "Privileged action executed through gate", "atb.profile.privileged_tool_action,atb.profile.data_export,atb.profile.human_override", "critical"},
	{TypeAIActionCommitted, "Privileged action committed to sink", "atb.profile.privileged_tool_action,atb.profile.data_export,atb.profile.human_override", "critical"},
	{TypeAIHumanApproval, "Human approval of an action or override", "atb.profile.privileged_tool_action,atb.profile.data_export,atb.profile.human_override", "required"},
	{TypeAIOverrideRequested, "Human override requested", "", "critical"},
	{TypeAIJobScheduled, "Background job scheduled", "atb.profile.background_automation", "critical"},
	{TypeAIJobStarted, "Background job started by worker", "atb.profile.background_automation", "critical"},
	{TypeAIJobStep, "Individual step within a background job", "atb.profile.background_automation", "critical"},
	{TypeAIJobCompleted, "Background job completed", "atb.profile.background_automation", "critical"},
	{TypeDataExportPrecommit, "Pre-commit record for a data export", "atb.profile.data_export", "critical"},
	{TypeDataExportExecuted, "Data export executed to sink", "atb.profile.data_export", "critical"},
	{TypeDevSession, "Developer session marker (tooling use)", "", "informational"},
	{TypeSnapshotBuild, "Build snapshot (tooling use)", "", "informational"},
	{TypeCorroborationExternal, "External corroboration record (adapter-retrieved evidence)", "", "informational"},
	{TypeRAGIndex, "PageIndex document tree build record (index_hash, node_count)", "atb.profile.rag_answer", "required"},
	{TypeRAGRetrieval, "PageIndex reasoning-based retrieval result (node_id, page_start/end)", "atb.profile.rag_answer", "required"},
}

// RequiredFieldsGenerated maps each event type to schema-declared required data fields.
var RequiredFieldsGenerated = map[string][]string{
	TypeBundleManifest:        []string{"version", "created_at", "bundle_id"},
	TypeBundleAnchor:          []string{"tsa_url", "bundle_hash", "tsr_hash", "tsr_der", "certified_time"},
	TypeBundleSignature:       []string{"bundle_hash", "signature", "pubkey"},
	TypeSnapshot:              []string{"name", "bundle_hash", "record_count", "snapshot_at"},
	TypeBundlePushed:          []string{},
	TypeAIRequestReceived:     []string{"request_id", "actor_id_hash", "purpose_tag"},
	TypeAIResponseSent:        []string{"request_id", "output_digest"},
	TypeAILLMCall:             []string{},
	TypeAIToolExec:            []string{},
	TypeAIChainRun:            []string{},
	TypeAIPolicyDecision:      []string{},
	TypeAIRetrievalExecuted:   []string{},
	TypeAIModelInvoked:        []string{"model_provider", "model_id", "model_parameters_digest", "prompt_digest"},
	TypeAIModelOutput:         []string{"output_digest", "output_format"},
	TypeAIActionPrecommit:     []string{"action_id", "action_type", "action_parameters_digest", "target_resource_id", "intended_effect"},
	TypeAIActionExecuted:      []string{"action_id", "execution_outcome", "tool_receipt_digest"},
	TypeAIActionCommitted:     []string{},
	TypeAIHumanApproval:       []string{},
	TypeAIOverrideRequested:   []string{},
	TypeAIJobScheduled:        []string{},
	TypeAIJobStarted:          []string{},
	TypeAIJobStep:             []string{},
	TypeAIJobCompleted:        []string{},
	TypeDataExportPrecommit:   []string{},
	TypeDataExportExecuted:    []string{},
	TypeDevSession:            []string{},
	TypeSnapshotBuild:         []string{},
	TypeCorroborationExternal: []string{},
	TypeRAGIndex:              []string{},
	TypeRAGRetrieval:          []string{},
}
