// Code generated by tools/eventgen; DO NOT EDIT.
// Source: schemas/event.v1.json event_types

package event

const (
	// TypeBundleManifest is "atb.bundle.manifest".
	TypeBundleManifest = "atb.bundle.manifest"
	// TypeBundleAnchor is "atb.bundle.anchor".
	TypeBundleAnchor = "atb.bundle.anchor"
	// TypeBundleSignature is "atb.bundle.signature".
	TypeBundleSignature = "atb.bundle.signature"
	// TypeSnapshot is "atb.snapshot".
	TypeSnapshot = "atb.snapshot"
	// TypeAIRequestReceived is "ai.request.received".
	TypeAIRequestReceived = "ai.request.received"
	// TypeAIResponseSent is "ai.response.sent".
	TypeAIResponseSent = "ai.response.sent"
	// TypeAILLMCall is "ai.llm.call".
	TypeAILLMCall = "ai.llm.call"
	// TypeAIToolExec is "ai.tool.exec".
	TypeAIToolExec = "ai.tool.exec"
	// TypeAIChainRun is "ai.chain.run".
	TypeAIChainRun = "ai.chain.run"
	// TypeAIPolicyDecision is "ai.policy.decision".
	TypeAIPolicyDecision = "ai.policy.decision"
	// TypeAIRetrievalExecuted is "ai.retrieval.executed".
	TypeAIRetrievalExecuted = "ai.retrieval.executed"
	// TypeAIModelInvoked is "ai.model.invoked".
	TypeAIModelInvoked = "ai.model.invoked"
	// TypeAIModelOutput is "ai.model.output".
	TypeAIModelOutput = "ai.model.output"
	// TypeAIActionPrecommit is "ai.action.precommit".
	TypeAIActionPrecommit = "ai.action.precommit"
	// TypeAIActionExecuted is "ai.action.executed".
	TypeAIActionExecuted = "ai.action.executed"
	// TypeAIActionCommitted is "ai.action.committed".
	TypeAIActionCommitted = "ai.action.committed"
	// TypeAIActionError is "ai.action.error".
	TypeAIActionError = "ai.action.error"
	// TypeAIHumanApproval is "ai.human.approval".
	TypeAIHumanApproval = "ai.human.approval"
	// TypeAIJobScheduled is "ai.job.scheduled".
	TypeAIJobScheduled = "ai.job.scheduled"
	// TypeAIJobStarted is "ai.job.started".
	TypeAIJobStarted = "ai.job.started"
	// TypeAIJobStep is "ai.job.step".
	TypeAIJobStep = "ai.job.step"
	// TypeAIJobCompleted is "ai.job.completed".
	TypeAIJobCompleted = "ai.job.completed"
	// TypeDataExportPrecommit is "data.export.precommit".
	TypeDataExportPrecommit = "data.export.precommit"
	// TypeDataExportExecuted is "data.export.executed".
	TypeDataExportExecuted = "data.export.executed"
	// TypeDataExportError is "data.export.error".
	TypeDataExportError = "data.export.error"
	// TypeDataRetentionPolicySet is "data.retention.policy_set".
	TypeDataRetentionPolicySet = "data.retention.policy_set"
	// TypeDataRetentionPolicyChanged is "data.retention.policy_changed".
	TypeDataRetentionPolicyChanged = "data.retention.policy_changed"
	// TypeDataRetentionEnforced is "data.retention.enforced".
	TypeDataRetentionEnforced = "data.retention.enforced"
	// TypeDevSession is "dev.session".
	TypeDevSession = "dev.session"
	// TypeCorroborationExternal is "atb.corroboration.external".
	TypeCorroborationExternal = "atb.corroboration.external"
	// TypeRAGIndex is "atb.event.rag_index".
	TypeRAGIndex = "atb.event.rag_index"
	// TypeRAGRetrieval is "atb.event.rag_retrieval".
	TypeRAGRetrieval = "atb.event.rag_retrieval"
	// TypeToolCall is "atb.tool.call".
	TypeToolCall = "atb.tool.call"
	// TypeDataExport is "atb.data.export".
	TypeDataExport = "atb.data.export"
	// TypeHumanOverride is "atb.human.override".
	TypeHumanOverride = "atb.human.override"
	// TypeHumanApproval is "atb.human.approval".
	TypeHumanApproval = "atb.human.approval"
	// TypeCaptureScope is "atb.capture.scope".
	TypeCaptureScope = "atb.capture.scope"
	// TypeCaptureRejected is "atb.capture.rejected".
	TypeCaptureRejected = "atb.capture.rejected"
	// TypeLLMRequest is "atb.llm.request".
	TypeLLMRequest = "atb.llm.request"
	// TypeLLMResponse is "atb.llm.response".
	TypeLLMResponse = "atb.llm.response"
	// TypeSessionClose is "atb.session.close".
	TypeSessionClose = "atb.session.close"
	// TypeExchangeComplete is "atb.exchange.complete".
	TypeExchangeComplete = "atb.exchange.complete"
)

// EventTypeSpecGenerated mirrors the schema event_types metadata block.
type EventTypeSpecGenerated struct {
	Type           string   `json:"type"`
	Description    string   `json:"description"`
	Profiles       []string `json:"profiles"`
	Criticality    string   `json:"criticality"`
	RequiredFields []string `json:"required_fields"`
}

// EventTypesGenerated is generated from schemas/event.v1.json event_types.
var EventTypesGenerated = []EventTypeSpecGenerated{
	{Type: TypeBundleManifest, Description: "Bundle manifest (seq 0, always first in a new bundle)", Profiles: []string{"atb.profile.privileged_tool_action", "atb.profile.rag_answer", "atb.profile.data_export", "atb.profile.policy_decision", "atb.profile.human_override", "atb.profile.background_automation"}, Criticality: "critical", RequiredFields: []string{"version", "created_at", "bundle_id"}},
	{Type: TypeBundleAnchor, Description: "RFC 3161 TSA timestamp anchor", Profiles: []string{"all"}, Criticality: "required", RequiredFields: []string{"tsa_url", "bundle_hash", "tsr_hash", "tsr_der", "certified_time"}},
	{Type: TypeBundleSignature, Description: "Ed25519 bundle signature", Profiles: []string{"all"}, Criticality: "required", RequiredFields: []string{"bundle_hash", "signature", "pubkey"}},
	{Type: TypeSnapshot, Description: "Bundle snapshot marker", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{"name", "bundle_hash", "record_count", "snapshot_at"}},
	{Type: TypeAIRequestReceived, Description: "AI request received at app boundary", Profiles: []string{"atb.profile.rag_answer", "atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.policy_decision", "atb.profile.human_override"}, Criticality: "critical", RequiredFields: []string{"request_id", "actor_id_hash", "purpose_tag"}},
	{Type: TypeAIResponseSent, Description: "AI response sent from app boundary", Profiles: []string{"atb.profile.rag_answer"}, Criticality: "required", RequiredFields: []string{"request_id", "output_digest"}},
	{Type: TypeAILLMCall, Description: "Canonical LLM lifecycle event for integrations", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{}},
	{Type: TypeAIToolExec, Description: "Canonical tool execution lifecycle event for integrations", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{}},
	{Type: TypeAIChainRun, Description: "Canonical chain or step lifecycle event for integrations", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{}},
	{Type: TypeAIPolicyDecision, Description: "Policy engine decision (allow/deny)", Profiles: []string{"atb.profile.privileged_tool_action", "atb.profile.rag_answer", "atb.profile.data_export", "atb.profile.policy_decision"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeAIRetrievalExecuted, Description: "Retrieval step executed (RAG)", Profiles: []string{"atb.profile.rag_answer"}, Criticality: "required", RequiredFields: []string{}},
	{Type: TypeAIModelInvoked, Description: "LLM invocation sent", Profiles: []string{"atb.profile.rag_answer"}, Criticality: "critical", RequiredFields: []string{"model_provider", "model_id", "model_parameters_digest", "prompt_digest"}},
	{Type: TypeAIModelOutput, Description: "LLM output received", Profiles: []string{"atb.profile.rag_answer"}, Criticality: "critical", RequiredFields: []string{"output_digest", "output_format"}},
	{Type: TypeAIActionPrecommit, Description: "Pre-commit record for a gated privileged action", Profiles: []string{"atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.policy_decision", "atb.profile.human_override"}, Criticality: "critical", RequiredFields: []string{"action_id", "action_type", "action_parameters_digest", "target_resource_id", "intended_effect"}},
	{Type: TypeAIActionExecuted, Description: "Privileged action executed through gate", Profiles: []string{"atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.human_override"}, Criticality: "critical", RequiredFields: []string{"action_id", "execution_outcome", "tool_receipt_digest"}},
	{Type: TypeAIActionCommitted, Description: "Privileged action committed to sink", Profiles: []string{"atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.human_override"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeAIActionError, Description: "Privileged action attempted but did not succeed (failed, blocked, timed out, or denied at the sink)", Profiles: []string{}, Criticality: "required", RequiredFields: []string{"action_id", "error_class"}},
	{Type: TypeAIHumanApproval, Description: "Human approval of an action or override", Profiles: []string{"atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.human_override"}, Criticality: "required", RequiredFields: []string{}},
	{Type: TypeAIJobScheduled, Description: "Background job scheduled", Profiles: []string{"atb.profile.background_automation"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeAIJobStarted, Description: "Background job started by worker", Profiles: []string{"atb.profile.background_automation"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeAIJobStep, Description: "Individual step within a background job", Profiles: []string{"atb.profile.background_automation"}, Criticality: "required", RequiredFields: []string{}},
	{Type: TypeAIJobCompleted, Description: "Background job completed", Profiles: []string{"atb.profile.background_automation"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeDataExportPrecommit, Description: "Pre-commit record for a data export", Profiles: []string{"atb.profile.data_export"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeDataExportExecuted, Description: "Data export executed to sink", Profiles: []string{"atb.profile.data_export"}, Criticality: "critical", RequiredFields: []string{}},
	{Type: TypeDataExportError, Description: "Data export attempted but did not succeed (failed, blocked, timed out, or denied at the sink)", Profiles: []string{}, Criticality: "required", RequiredFields: []string{"action_id", "error_class"}},
	{Type: TypeDataRetentionPolicySet, Description: "Deployment retention policy configured", Profiles: []string{}, Criticality: "required", RequiredFields: []string{"policy_id", "days", "archive_dir", "scope", "cutoff_basis", "config_digest"}},
	{Type: TypeDataRetentionPolicyChanged, Description: "Deployment retention policy changed", Profiles: []string{}, Criticality: "required", RequiredFields: []string{"policy_id", "days", "archive_dir", "scope", "cutoff_basis", "config_digest", "previous_config_digest"}},
	{Type: TypeDataRetentionEnforced, Description: "Retention-relevant local operation completed or remote retention request accepted", Profiles: []string{}, Criticality: "required", RequiredFields: []string{"operation", "enforcement_system", "outcome", "evidence_level", "independently_verified"}},
	{Type: TypeDevSession, Description: "Developer session marker (tooling use)", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{}},
	{Type: TypeCorroborationExternal, Description: "External corroboration record (adapter-retrieved evidence)", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{}},
	{Type: TypeRAGIndex, Description: "PageIndex document tree build record (index_hash, node_count)", Profiles: []string{"atb.profile.rag_answer"}, Criticality: "required", RequiredFields: []string{}},
	{Type: TypeRAGRetrieval, Description: "PageIndex reasoning-based retrieval result (node_id, page_start/end)", Profiles: []string{"atb.profile.rag_answer"}, Criticality: "required", RequiredFields: []string{}},
	{Type: TypeToolCall, Description: "Tool invocation recorded for session oversight", Profiles: []string{}, Criticality: "required", RequiredFields: []string{"session_id", "tool_name"}},
	{Type: TypeDataExport, Description: "Data export outside session boundary", Profiles: []string{}, Criticality: "required", RequiredFields: []string{"session_id", "export_target"}},
	{Type: TypeHumanOverride, Description: "Human operator overrode an AI-recommended action", Profiles: []string{}, Criticality: "required", RequiredFields: []string{"session_id", "override_reason"}},
	{Type: TypeHumanApproval, Description: "Human operator approved a pending action", Profiles: []string{}, Criticality: "required", RequiredFields: []string{"session_id", "approved_action_id"}},
	{Type: TypeCaptureScope, Description: "Capture-coverage attestation written by atb intercept at startup: what the recorder can and cannot see", Profiles: []string{}, Criticality: "required", RequiredFields: []string{"targets", "capture_mode"}},
	{Type: TypeCaptureRejected, Description: "Capture rejection or incomplete exchange (proxy-internal)", Profiles: []string{}, Criticality: "required", RequiredFields: []string{"session_id", "host", "method", "path", "direction", "reason", "limit_bytes", "observed_bytes"}},
	{Type: TypeLLMRequest, Description: "Captured upstream LLM API request (proxy-internal)", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{"session_id", "host", "method", "path"}},
	{Type: TypeLLMResponse, Description: "Captured upstream LLM API response (proxy-internal)", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{"session_id", "host", "method", "path", "status_code"}},
	{Type: TypeSessionClose, Description: "Capture session closed (proxy-internal lifecycle marker)", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{"session_id", "actor_id"}},
	{Type: TypeExchangeComplete, Description: "Request/response exchange completed within a capture session (proxy-internal)", Profiles: []string{}, Criticality: "informational", RequiredFields: []string{"session_id", "exchange_id", "request_event_id"}},
}

// RegistryGenerated is the EventInfo view generated from schemas/event.v1.json event_types.
var RegistryGenerated = []EventInfo{
	{TypeBundleManifest, "Bundle manifest (seq 0, always first in a new bundle)", "atb.profile.privileged_tool_action,atb.profile.rag_answer,atb.profile.data_export,atb.profile.policy_decision,atb.profile.human_override,atb.profile.background_automation", "critical"},
	{TypeBundleAnchor, "RFC 3161 TSA timestamp anchor", "all", "required"},
	{TypeBundleSignature, "Ed25519 bundle signature", "all", "required"},
	{TypeSnapshot, "Bundle snapshot marker", "", "informational"},
	{TypeAIRequestReceived, "AI request received at app boundary", "atb.profile.rag_answer,atb.profile.privileged_tool_action,atb.profile.data_export,atb.profile.policy_decision,atb.profile.human_override", "critical"},
	{TypeAIResponseSent, "AI response sent from app boundary", "atb.profile.rag_answer", "required"},
	{TypeAILLMCall, "Canonical LLM lifecycle event for integrations", "", "informational"},
	{TypeAIToolExec, "Canonical tool execution lifecycle event for integrations", "", "informational"},
	{TypeAIChainRun, "Canonical chain or step lifecycle event for integrations", "", "informational"},
	{TypeAIPolicyDecision, "Policy engine decision (allow/deny)", "atb.profile.privileged_tool_action,atb.profile.rag_answer,atb.profile.data_export,atb.profile.policy_decision", "critical"},
	{TypeAIRetrievalExecuted, "Retrieval step executed (RAG)", "atb.profile.rag_answer", "required"},
	{TypeAIModelInvoked, "LLM invocation sent", "atb.profile.rag_answer", "critical"},
	{TypeAIModelOutput, "LLM output received", "atb.profile.rag_answer", "critical"},
	{TypeAIActionPrecommit, "Pre-commit record for a gated privileged action", "atb.profile.privileged_tool_action,atb.profile.data_export,atb.profile.policy_decision,atb.profile.human_override", "critical"},
	{TypeAIActionExecuted, "Privileged action executed through gate", "atb.profile.privileged_tool_action,atb.profile.data_export,atb.profile.human_override", "critical"},
	{TypeAIActionCommitted, "Privileged action committed to sink", "atb.profile.privileged_tool_action,atb.profile.data_export,atb.profile.human_override", "critical"},
	{TypeAIActionError, "Privileged action attempted but did not succeed (failed, blocked, timed out, or denied at the sink)", "", "required"},
	{TypeAIHumanApproval, "Human approval of an action or override", "atb.profile.privileged_tool_action,atb.profile.data_export,atb.profile.human_override", "required"},
	{TypeAIJobScheduled, "Background job scheduled", "atb.profile.background_automation", "critical"},
	{TypeAIJobStarted, "Background job started by worker", "atb.profile.background_automation", "critical"},
	{TypeAIJobStep, "Individual step within a background job", "atb.profile.background_automation", "required"},
	{TypeAIJobCompleted, "Background job completed", "atb.profile.background_automation", "critical"},
	{TypeDataExportPrecommit, "Pre-commit record for a data export", "atb.profile.data_export", "critical"},
	{TypeDataExportExecuted, "Data export executed to sink", "atb.profile.data_export", "critical"},
	{TypeDataExportError, "Data export attempted but did not succeed (failed, blocked, timed out, or denied at the sink)", "", "required"},
	{TypeDataRetentionPolicySet, "Deployment retention policy configured", "", "required"},
	{TypeDataRetentionPolicyChanged, "Deployment retention policy changed", "", "required"},
	{TypeDataRetentionEnforced, "Retention-relevant local operation completed or remote retention request accepted", "", "required"},
	{TypeDevSession, "Developer session marker (tooling use)", "", "informational"},
	{TypeCorroborationExternal, "External corroboration record (adapter-retrieved evidence)", "", "informational"},
	{TypeRAGIndex, "PageIndex document tree build record (index_hash, node_count)", "atb.profile.rag_answer", "required"},
	{TypeRAGRetrieval, "PageIndex reasoning-based retrieval result (node_id, page_start/end)", "atb.profile.rag_answer", "required"},
	{TypeToolCall, "Tool invocation recorded for session oversight", "", "required"},
	{TypeDataExport, "Data export outside session boundary", "", "required"},
	{TypeHumanOverride, "Human operator overrode an AI-recommended action", "", "required"},
	{TypeHumanApproval, "Human operator approved a pending action", "", "required"},
	{TypeCaptureScope, "Capture-coverage attestation written by atb intercept at startup: what the recorder can and cannot see", "", "required"},
	{TypeCaptureRejected, "Capture rejection or incomplete exchange (proxy-internal)", "", "required"},
	{TypeLLMRequest, "Captured upstream LLM API request (proxy-internal)", "", "informational"},
	{TypeLLMResponse, "Captured upstream LLM API response (proxy-internal)", "", "informational"},
	{TypeSessionClose, "Capture session closed (proxy-internal lifecycle marker)", "", "informational"},
	{TypeExchangeComplete, "Request/response exchange completed within a capture session (proxy-internal)", "", "informational"},
}

// RequiredFieldsGenerated maps each event type to schema-declared required data fields.
var RequiredFieldsGenerated = map[string][]string{
	TypeBundleManifest:             []string{"version", "created_at", "bundle_id"},
	TypeBundleAnchor:               []string{"tsa_url", "bundle_hash", "tsr_hash", "tsr_der", "certified_time"},
	TypeBundleSignature:            []string{"bundle_hash", "signature", "pubkey"},
	TypeSnapshot:                   []string{"name", "bundle_hash", "record_count", "snapshot_at"},
	TypeAIRequestReceived:          []string{"request_id", "actor_id_hash", "purpose_tag"},
	TypeAIResponseSent:             []string{"request_id", "output_digest"},
	TypeAILLMCall:                  []string{},
	TypeAIToolExec:                 []string{},
	TypeAIChainRun:                 []string{},
	TypeAIPolicyDecision:           []string{},
	TypeAIRetrievalExecuted:        []string{},
	TypeAIModelInvoked:             []string{"model_provider", "model_id", "model_parameters_digest", "prompt_digest"},
	TypeAIModelOutput:              []string{"output_digest", "output_format"},
	TypeAIActionPrecommit:          []string{"action_id", "action_type", "action_parameters_digest", "target_resource_id", "intended_effect"},
	TypeAIActionExecuted:           []string{"action_id", "execution_outcome", "tool_receipt_digest"},
	TypeAIActionCommitted:          []string{},
	TypeAIActionError:              []string{"action_id", "error_class"},
	TypeAIHumanApproval:            []string{},
	TypeAIJobScheduled:             []string{},
	TypeAIJobStarted:               []string{},
	TypeAIJobStep:                  []string{},
	TypeAIJobCompleted:             []string{},
	TypeDataExportPrecommit:        []string{},
	TypeDataExportExecuted:         []string{},
	TypeDataExportError:            []string{"action_id", "error_class"},
	TypeDataRetentionPolicySet:     []string{"policy_id", "days", "archive_dir", "scope", "cutoff_basis", "config_digest"},
	TypeDataRetentionPolicyChanged: []string{"policy_id", "days", "archive_dir", "scope", "cutoff_basis", "config_digest", "previous_config_digest"},
	TypeDataRetentionEnforced:      []string{"operation", "enforcement_system", "outcome", "evidence_level", "independently_verified"},
	TypeDevSession:                 []string{},
	TypeCorroborationExternal:      []string{},
	TypeRAGIndex:                   []string{},
	TypeRAGRetrieval:               []string{},
	TypeToolCall:                   []string{"session_id", "tool_name"},
	TypeDataExport:                 []string{"session_id", "export_target"},
	TypeHumanOverride:              []string{"session_id", "override_reason"},
	TypeHumanApproval:              []string{"session_id", "approved_action_id"},
	TypeCaptureScope:               []string{"targets", "capture_mode"},
	TypeCaptureRejected:            []string{"session_id", "host", "method", "path", "direction", "reason", "limit_bytes", "observed_bytes"},
	TypeLLMRequest:                 []string{"session_id", "host", "method", "path"},
	TypeLLMResponse:                []string{"session_id", "host", "method", "path", "status_code"},
	TypeSessionClose:               []string{"session_id", "actor_id"},
	TypeExchangeComplete:           []string{"session_id", "exchange_id", "request_event_id"},
}
