"""Canonical ATB event type constants aligned with the Go runtime."""

BUNDLE_MANIFEST_EVENT_TYPE = "atb.bundle.manifest"
BUNDLE_ANCHOR_EVENT_TYPE = "atb.bundle.anchor"
BUNDLE_SIGNATURE_EVENT_TYPE = "atb.bundle.signature"

AI_REQUEST_RECEIVED_EVENT_TYPE = "ai.request.received"
AI_RESPONSE_SENT_EVENT_TYPE = "ai.response.sent"
AI_POLICY_DECISION_EVENT_TYPE = "ai.policy.decision"

AI_RETRIEVAL_EXECUTED_EVENT_TYPE = "ai.retrieval.executed"
AI_MODEL_INVOKED_EVENT_TYPE = "ai.model.invoked"
AI_MODEL_OUTPUT_EVENT_TYPE = "ai.model.output"

AI_ACTION_PRECOMMIT_EVENT_TYPE = "ai.action.precommit"
AI_ACTION_EXECUTED_EVENT_TYPE = "ai.action.executed"
AI_ACTION_COMMITTED_EVENT_TYPE = "ai.action.committed"

AI_HUMAN_APPROVAL_EVENT_TYPE = "ai.human.approval"

AI_JOB_SCHEDULED_EVENT_TYPE = "ai.job.scheduled"
AI_JOB_STARTED_EVENT_TYPE = "ai.job.started"
AI_JOB_STEP_EVENT_TYPE = "ai.job.step"
AI_JOB_COMPLETED_EVENT_TYPE = "ai.job.completed"

DATA_EXPORT_PRECOMMIT_EVENT_TYPE = "data.export.precommit"
DATA_EXPORT_EXECUTED_EVENT_TYPE = "data.export.executed"

__all__ = [
    "BUNDLE_MANIFEST_EVENT_TYPE",
    "BUNDLE_ANCHOR_EVENT_TYPE",
    "BUNDLE_SIGNATURE_EVENT_TYPE",
    "AI_REQUEST_RECEIVED_EVENT_TYPE",
    "AI_RESPONSE_SENT_EVENT_TYPE",
    "AI_POLICY_DECISION_EVENT_TYPE",
    "AI_RETRIEVAL_EXECUTED_EVENT_TYPE",
    "AI_MODEL_INVOKED_EVENT_TYPE",
    "AI_MODEL_OUTPUT_EVENT_TYPE",
    "AI_ACTION_PRECOMMIT_EVENT_TYPE",
    "AI_ACTION_EXECUTED_EVENT_TYPE",
    "AI_ACTION_COMMITTED_EVENT_TYPE",
    "AI_HUMAN_APPROVAL_EVENT_TYPE",
    "AI_JOB_SCHEDULED_EVENT_TYPE",
    "AI_JOB_STARTED_EVENT_TYPE",
    "AI_JOB_STEP_EVENT_TYPE",
    "AI_JOB_COMPLETED_EVENT_TYPE",
    "DATA_EXPORT_PRECOMMIT_EVENT_TYPE",
    "DATA_EXPORT_EXECUTED_EVENT_TYPE",
]
