# Code generated by tools/eventgen; DO NOT EDIT.
# Source: schemas/event.v1.json event_types
# ruff: noqa
from __future__ import annotations

from typing import Final, TypedDict


class EventTypeSpec(TypedDict):
    type: str
    description: str
    profiles: list[str]
    criticality: str
    required_fields: list[str]


BUNDLE_MANIFEST: Final = "atb.bundle.manifest"
BUNDLE_MANIFEST_EVENT_TYPE: Final = BUNDLE_MANIFEST

BUNDLE_ANCHOR: Final = "atb.bundle.anchor"
BUNDLE_ANCHOR_EVENT_TYPE: Final = BUNDLE_ANCHOR

BUNDLE_SIGNATURE: Final = "atb.bundle.signature"
BUNDLE_SIGNATURE_EVENT_TYPE: Final = BUNDLE_SIGNATURE

SNAPSHOT: Final = "atb.snapshot"
SNAPSHOT_EVENT_TYPE: Final = SNAPSHOT

BUNDLE_PUSHED: Final = "atb.bundle.pushed"
BUNDLE_PUSHED_EVENT_TYPE: Final = BUNDLE_PUSHED

AI_REQUEST_RECEIVED: Final = "ai.request.received"
AI_REQUEST_RECEIVED_EVENT_TYPE: Final = AI_REQUEST_RECEIVED

AI_RESPONSE_SENT: Final = "ai.response.sent"
AI_RESPONSE_SENT_EVENT_TYPE: Final = AI_RESPONSE_SENT

AI_LLM_CALL: Final = "ai.llm.call"
AI_LLM_CALL_EVENT_TYPE: Final = AI_LLM_CALL

AI_TOOL_EXEC: Final = "ai.tool.exec"
AI_TOOL_EXEC_EVENT_TYPE: Final = AI_TOOL_EXEC

AI_CHAIN_RUN: Final = "ai.chain.run"
AI_CHAIN_RUN_EVENT_TYPE: Final = AI_CHAIN_RUN

AI_POLICY_DECISION: Final = "ai.policy.decision"
AI_POLICY_DECISION_EVENT_TYPE: Final = AI_POLICY_DECISION

AI_RETRIEVAL_EXECUTED: Final = "ai.retrieval.executed"
AI_RETRIEVAL_EXECUTED_EVENT_TYPE: Final = AI_RETRIEVAL_EXECUTED

AI_MODEL_INVOKED: Final = "ai.model.invoked"
AI_MODEL_INVOKED_EVENT_TYPE: Final = AI_MODEL_INVOKED

AI_MODEL_OUTPUT: Final = "ai.model.output"
AI_MODEL_OUTPUT_EVENT_TYPE: Final = AI_MODEL_OUTPUT

AI_ACTION_PRECOMMIT: Final = "ai.action.precommit"
AI_ACTION_PRECOMMIT_EVENT_TYPE: Final = AI_ACTION_PRECOMMIT

AI_ACTION_EXECUTED: Final = "ai.action.executed"
AI_ACTION_EXECUTED_EVENT_TYPE: Final = AI_ACTION_EXECUTED

AI_ACTION_COMMITTED: Final = "ai.action.committed"
AI_ACTION_COMMITTED_EVENT_TYPE: Final = AI_ACTION_COMMITTED

AI_HUMAN_APPROVAL: Final = "ai.human.approval"
AI_HUMAN_APPROVAL_EVENT_TYPE: Final = AI_HUMAN_APPROVAL

AI_OVERRIDE_REQUESTED: Final = "ai.override.requested"
AI_OVERRIDE_REQUESTED_EVENT_TYPE: Final = AI_OVERRIDE_REQUESTED

AI_JOB_SCHEDULED: Final = "ai.job.scheduled"
AI_JOB_SCHEDULED_EVENT_TYPE: Final = AI_JOB_SCHEDULED

AI_JOB_STARTED: Final = "ai.job.started"
AI_JOB_STARTED_EVENT_TYPE: Final = AI_JOB_STARTED

AI_JOB_STEP: Final = "ai.job.step"
AI_JOB_STEP_EVENT_TYPE: Final = AI_JOB_STEP

AI_JOB_COMPLETED: Final = "ai.job.completed"
AI_JOB_COMPLETED_EVENT_TYPE: Final = AI_JOB_COMPLETED

DATA_EXPORT_PRECOMMIT: Final = "data.export.precommit"
DATA_EXPORT_PRECOMMIT_EVENT_TYPE: Final = DATA_EXPORT_PRECOMMIT

DATA_EXPORT_EXECUTED: Final = "data.export.executed"
DATA_EXPORT_EXECUTED_EVENT_TYPE: Final = DATA_EXPORT_EXECUTED

DEV_SESSION: Final = "dev.session"
DEV_SESSION_EVENT_TYPE: Final = DEV_SESSION

SNAPSHOT_BUILD: Final = "snapshot.build"
SNAPSHOT_BUILD_EVENT_TYPE: Final = SNAPSHOT_BUILD

CORROBORATION_EXTERNAL: Final = "atb.corroboration.external"
CORROBORATION_EXTERNAL_EVENT_TYPE: Final = CORROBORATION_EXTERNAL

RAG_INDEX: Final = "atb.event.rag_index"
RAG_INDEX_EVENT_TYPE: Final = RAG_INDEX

RAG_RETRIEVAL: Final = "atb.event.rag_retrieval"
RAG_RETRIEVAL_EVENT_TYPE: Final = RAG_RETRIEVAL

TOOL_CALL: Final = "atb.tool.call"
TOOL_CALL_EVENT_TYPE: Final = TOOL_CALL

DATA_EXPORT: Final = "atb.data.export"
DATA_EXPORT_EVENT_TYPE: Final = DATA_EXPORT

HUMAN_OVERRIDE: Final = "atb.human.override"
HUMAN_OVERRIDE_EVENT_TYPE: Final = HUMAN_OVERRIDE

HUMAN_APPROVAL: Final = "atb.human.approval"
HUMAN_APPROVAL_EVENT_TYPE: Final = HUMAN_APPROVAL

SESSION_CLOSE: Final = "atb.session.close"
SESSION_CLOSE_EVENT_TYPE: Final = SESSION_CLOSE

EXCHANGE_COMPLETE: Final = "atb.exchange.complete"
EXCHANGE_COMPLETE_EVENT_TYPE: Final = EXCHANGE_COMPLETE

EVENT_TYPE_REGISTRY: list[EventTypeSpec] = [
    {
        "type": BUNDLE_MANIFEST,
        "description": "Bundle manifest (seq 0, always first in a new bundle)",
        "profiles": ["atb.profile.privileged_tool_action", "atb.profile.rag_answer", "atb.profile.data_export", "atb.profile.policy_decision", "atb.profile.human_override", "atb.profile.background_automation"],
        "criticality": "critical",
        "required_fields": ["version", "created_at", "bundle_id"],
    },
    {
        "type": BUNDLE_ANCHOR,
        "description": "RFC 3161 TSA timestamp anchor",
        "profiles": ["all"],
        "criticality": "required",
        "required_fields": ["tsa_url", "bundle_hash", "tsr_hash", "tsr_der", "certified_time"],
    },
    {
        "type": BUNDLE_SIGNATURE,
        "description": "Ed25519 bundle signature",
        "profiles": ["all"],
        "criticality": "required",
        "required_fields": ["bundle_hash", "signature", "pubkey"],
    },
    {
        "type": SNAPSHOT,
        "description": "Bundle snapshot marker",
        "profiles": [],
        "criticality": "informational",
        "required_fields": ["name", "bundle_hash", "record_count", "snapshot_at"],
    },
    {
        "type": BUNDLE_PUSHED,
        "description": "Bundle pushed to remote WORM target (atb push)",
        "profiles": [],
        "criticality": "informational",
        "required_fields": [],
    },
    {
        "type": AI_REQUEST_RECEIVED,
        "description": "AI request received at app boundary",
        "profiles": ["atb.profile.rag_answer", "atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.policy_decision", "atb.profile.human_override"],
        "criticality": "critical",
        "required_fields": ["request_id", "actor_id_hash", "purpose_tag"],
    },
    {
        "type": AI_RESPONSE_SENT,
        "description": "AI response sent from app boundary",
        "profiles": ["atb.profile.rag_answer"],
        "criticality": "required",
        "required_fields": ["request_id", "output_digest"],
    },
    {
        "type": AI_LLM_CALL,
        "description": "Canonical LLM lifecycle event for integrations",
        "profiles": [],
        "criticality": "informational",
        "required_fields": [],
    },
    {
        "type": AI_TOOL_EXEC,
        "description": "Canonical tool execution lifecycle event for integrations",
        "profiles": [],
        "criticality": "informational",
        "required_fields": [],
    },
    {
        "type": AI_CHAIN_RUN,
        "description": "Canonical chain or step lifecycle event for integrations",
        "profiles": [],
        "criticality": "informational",
        "required_fields": [],
    },
    {
        "type": AI_POLICY_DECISION,
        "description": "Policy engine decision (allow/deny)",
        "profiles": ["atb.profile.privileged_tool_action", "atb.profile.rag_answer", "atb.profile.data_export", "atb.profile.policy_decision"],
        "criticality": "critical",
        "required_fields": [],
    },
    {
        "type": AI_RETRIEVAL_EXECUTED,
        "description": "Retrieval step executed (RAG)",
        "profiles": ["atb.profile.rag_answer"],
        "criticality": "required",
        "required_fields": [],
    },
    {
        "type": AI_MODEL_INVOKED,
        "description": "LLM invocation sent",
        "profiles": ["atb.profile.rag_answer"],
        "criticality": "critical",
        "required_fields": ["model_provider", "model_id", "model_parameters_digest", "prompt_digest"],
    },
    {
        "type": AI_MODEL_OUTPUT,
        "description": "LLM output received",
        "profiles": ["atb.profile.rag_answer"],
        "criticality": "critical",
        "required_fields": ["output_digest", "output_format"],
    },
    {
        "type": AI_ACTION_PRECOMMIT,
        "description": "Pre-commit record for a gated privileged action",
        "profiles": ["atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.policy_decision", "atb.profile.human_override"],
        "criticality": "critical",
        "required_fields": ["action_id", "action_type", "action_parameters_digest", "target_resource_id", "intended_effect"],
    },
    {
        "type": AI_ACTION_EXECUTED,
        "description": "Privileged action executed through gate",
        "profiles": ["atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.human_override"],
        "criticality": "critical",
        "required_fields": ["action_id", "execution_outcome", "tool_receipt_digest"],
    },
    {
        "type": AI_ACTION_COMMITTED,
        "description": "Privileged action committed to sink",
        "profiles": ["atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.human_override"],
        "criticality": "critical",
        "required_fields": [],
    },
    {
        "type": AI_HUMAN_APPROVAL,
        "description": "Human approval of an action or override",
        "profiles": ["atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.human_override"],
        "criticality": "required",
        "required_fields": [],
    },
    {
        "type": AI_OVERRIDE_REQUESTED,
        "description": "Human override requested",
        "profiles": [],
        "criticality": "critical",
        "required_fields": [],
    },
    {
        "type": AI_JOB_SCHEDULED,
        "description": "Background job scheduled",
        "profiles": ["atb.profile.background_automation"],
        "criticality": "critical",
        "required_fields": [],
    },
    {
        "type": AI_JOB_STARTED,
        "description": "Background job started by worker",
        "profiles": ["atb.profile.background_automation"],
        "criticality": "critical",
        "required_fields": [],
    },
    {
        "type": AI_JOB_STEP,
        "description": "Individual step within a background job",
        "profiles": ["atb.profile.background_automation"],
        "criticality": "critical",
        "required_fields": [],
    },
    {
        "type": AI_JOB_COMPLETED,
        "description": "Background job completed",
        "profiles": ["atb.profile.background_automation"],
        "criticality": "critical",
        "required_fields": [],
    },
    {
        "type": DATA_EXPORT_PRECOMMIT,
        "description": "Pre-commit record for a data export",
        "profiles": ["atb.profile.data_export"],
        "criticality": "critical",
        "required_fields": [],
    },
    {
        "type": DATA_EXPORT_EXECUTED,
        "description": "Data export executed to sink",
        "profiles": ["atb.profile.data_export"],
        "criticality": "critical",
        "required_fields": [],
    },
    {
        "type": DEV_SESSION,
        "description": "Developer session marker (tooling use)",
        "profiles": [],
        "criticality": "informational",
        "required_fields": [],
    },
    {
        "type": SNAPSHOT_BUILD,
        "description": "Build snapshot (tooling use)",
        "profiles": [],
        "criticality": "informational",
        "required_fields": [],
    },
    {
        "type": CORROBORATION_EXTERNAL,
        "description": "External corroboration record (adapter-retrieved evidence)",
        "profiles": [],
        "criticality": "informational",
        "required_fields": [],
    },
    {
        "type": RAG_INDEX,
        "description": "PageIndex document tree build record (index_hash, node_count)",
        "profiles": ["atb.profile.rag_answer"],
        "criticality": "required",
        "required_fields": [],
    },
    {
        "type": RAG_RETRIEVAL,
        "description": "PageIndex reasoning-based retrieval result (node_id, page_start/end)",
        "profiles": ["atb.profile.rag_answer"],
        "criticality": "required",
        "required_fields": [],
    },
    {
        "type": TOOL_CALL,
        "description": "Tool invocation recorded for session oversight",
        "profiles": [],
        "criticality": "required",
        "required_fields": ["session_id", "tool_name"],
    },
    {
        "type": DATA_EXPORT,
        "description": "Data export outside session boundary",
        "profiles": [],
        "criticality": "required",
        "required_fields": ["session_id", "export_target"],
    },
    {
        "type": HUMAN_OVERRIDE,
        "description": "Human operator overrode an AI-recommended action",
        "profiles": [],
        "criticality": "required",
        "required_fields": ["session_id", "override_reason"],
    },
    {
        "type": HUMAN_APPROVAL,
        "description": "Human operator approved a pending action",
        "profiles": [],
        "criticality": "required",
        "required_fields": ["session_id", "approved_action_id"],
    },
    {
        "type": SESSION_CLOSE,
        "description": "Capture session closed (proxy-internal lifecycle marker)",
        "profiles": [],
        "criticality": "informational",
        "required_fields": ["session_id", "actor_id"],
    },
    {
        "type": EXCHANGE_COMPLETE,
        "description": "Request/response exchange completed within a capture session (proxy-internal)",
        "profiles": [],
        "criticality": "informational",
        "required_fields": ["session_id", "exchange_id", "request_event_id"],
    },
]

EVENT_TYPE_REQUIRED_FIELDS: dict[str, list[str]] = {
    BUNDLE_MANIFEST: ["version", "created_at", "bundle_id"],
    BUNDLE_ANCHOR: ["tsa_url", "bundle_hash", "tsr_hash", "tsr_der", "certified_time"],
    BUNDLE_SIGNATURE: ["bundle_hash", "signature", "pubkey"],
    SNAPSHOT: ["name", "bundle_hash", "record_count", "snapshot_at"],
    BUNDLE_PUSHED: [],
    AI_REQUEST_RECEIVED: ["request_id", "actor_id_hash", "purpose_tag"],
    AI_RESPONSE_SENT: ["request_id", "output_digest"],
    AI_LLM_CALL: [],
    AI_TOOL_EXEC: [],
    AI_CHAIN_RUN: [],
    AI_POLICY_DECISION: [],
    AI_RETRIEVAL_EXECUTED: [],
    AI_MODEL_INVOKED: ["model_provider", "model_id", "model_parameters_digest", "prompt_digest"],
    AI_MODEL_OUTPUT: ["output_digest", "output_format"],
    AI_ACTION_PRECOMMIT: ["action_id", "action_type", "action_parameters_digest", "target_resource_id", "intended_effect"],
    AI_ACTION_EXECUTED: ["action_id", "execution_outcome", "tool_receipt_digest"],
    AI_ACTION_COMMITTED: [],
    AI_HUMAN_APPROVAL: [],
    AI_OVERRIDE_REQUESTED: [],
    AI_JOB_SCHEDULED: [],
    AI_JOB_STARTED: [],
    AI_JOB_STEP: [],
    AI_JOB_COMPLETED: [],
    DATA_EXPORT_PRECOMMIT: [],
    DATA_EXPORT_EXECUTED: [],
    DEV_SESSION: [],
    SNAPSHOT_BUILD: [],
    CORROBORATION_EXTERNAL: [],
    RAG_INDEX: [],
    RAG_RETRIEVAL: [],
    TOOL_CALL: ["session_id", "tool_name"],
    DATA_EXPORT: ["session_id", "export_target"],
    HUMAN_OVERRIDE: ["session_id", "override_reason"],
    HUMAN_APPROVAL: ["session_id", "approved_action_id"],
    SESSION_CLOSE: ["session_id", "actor_id"],
    EXCHANGE_COMPLETE: ["session_id", "exchange_id", "request_event_id"],
}

__all__ = [
    "EventTypeSpec",
    "EVENT_TYPE_REGISTRY",
    "EVENT_TYPE_REQUIRED_FIELDS",
    "BUNDLE_MANIFEST",
    "BUNDLE_MANIFEST_EVENT_TYPE",
    "BUNDLE_ANCHOR",
    "BUNDLE_ANCHOR_EVENT_TYPE",
    "BUNDLE_SIGNATURE",
    "BUNDLE_SIGNATURE_EVENT_TYPE",
    "SNAPSHOT",
    "SNAPSHOT_EVENT_TYPE",
    "BUNDLE_PUSHED",
    "BUNDLE_PUSHED_EVENT_TYPE",
    "AI_REQUEST_RECEIVED",
    "AI_REQUEST_RECEIVED_EVENT_TYPE",
    "AI_RESPONSE_SENT",
    "AI_RESPONSE_SENT_EVENT_TYPE",
    "AI_LLM_CALL",
    "AI_LLM_CALL_EVENT_TYPE",
    "AI_TOOL_EXEC",
    "AI_TOOL_EXEC_EVENT_TYPE",
    "AI_CHAIN_RUN",
    "AI_CHAIN_RUN_EVENT_TYPE",
    "AI_POLICY_DECISION",
    "AI_POLICY_DECISION_EVENT_TYPE",
    "AI_RETRIEVAL_EXECUTED",
    "AI_RETRIEVAL_EXECUTED_EVENT_TYPE",
    "AI_MODEL_INVOKED",
    "AI_MODEL_INVOKED_EVENT_TYPE",
    "AI_MODEL_OUTPUT",
    "AI_MODEL_OUTPUT_EVENT_TYPE",
    "AI_ACTION_PRECOMMIT",
    "AI_ACTION_PRECOMMIT_EVENT_TYPE",
    "AI_ACTION_EXECUTED",
    "AI_ACTION_EXECUTED_EVENT_TYPE",
    "AI_ACTION_COMMITTED",
    "AI_ACTION_COMMITTED_EVENT_TYPE",
    "AI_HUMAN_APPROVAL",
    "AI_HUMAN_APPROVAL_EVENT_TYPE",
    "AI_OVERRIDE_REQUESTED",
    "AI_OVERRIDE_REQUESTED_EVENT_TYPE",
    "AI_JOB_SCHEDULED",
    "AI_JOB_SCHEDULED_EVENT_TYPE",
    "AI_JOB_STARTED",
    "AI_JOB_STARTED_EVENT_TYPE",
    "AI_JOB_STEP",
    "AI_JOB_STEP_EVENT_TYPE",
    "AI_JOB_COMPLETED",
    "AI_JOB_COMPLETED_EVENT_TYPE",
    "DATA_EXPORT_PRECOMMIT",
    "DATA_EXPORT_PRECOMMIT_EVENT_TYPE",
    "DATA_EXPORT_EXECUTED",
    "DATA_EXPORT_EXECUTED_EVENT_TYPE",
    "DEV_SESSION",
    "DEV_SESSION_EVENT_TYPE",
    "SNAPSHOT_BUILD",
    "SNAPSHOT_BUILD_EVENT_TYPE",
    "CORROBORATION_EXTERNAL",
    "CORROBORATION_EXTERNAL_EVENT_TYPE",
    "RAG_INDEX",
    "RAG_INDEX_EVENT_TYPE",
    "RAG_RETRIEVAL",
    "RAG_RETRIEVAL_EVENT_TYPE",
    "TOOL_CALL",
    "TOOL_CALL_EVENT_TYPE",
    "DATA_EXPORT",
    "DATA_EXPORT_EVENT_TYPE",
    "HUMAN_OVERRIDE",
    "HUMAN_OVERRIDE_EVENT_TYPE",
    "HUMAN_APPROVAL",
    "HUMAN_APPROVAL_EVENT_TYPE",
    "SESSION_CLOSE",
    "SESSION_CLOSE_EVENT_TYPE",
    "EXCHANGE_COMPLETE",
    "EXCHANGE_COMPLETE_EVENT_TYPE",
]
