"""Canonical ATB event type constants aligned with the Go runtime."""

BUNDLE_MANIFEST_EVENT_TYPE = "atb.bundle.manifest"
BUNDLE_ANCHOR_EVENT_TYPE = "atb.bundle.anchor"
BUNDLE_SIGNATURE_EVENT_TYPE = "atb.bundle.signature"
SNAPSHOT_EVENT_TYPE = "atb.snapshot"

AI_REQUEST_RECEIVED_EVENT_TYPE = "ai.request.received"
AI_RESPONSE_SENT_EVENT_TYPE = "ai.response.sent"
AI_LLM_CALL_EVENT_TYPE = "ai.llm.call"
AI_TOOL_EXEC_EVENT_TYPE = "ai.tool.exec"
AI_CHAIN_RUN_EVENT_TYPE = "ai.chain.run"
AI_POLICY_DECISION_EVENT_TYPE = "ai.policy.decision"

AI_RETRIEVAL_EXECUTED_EVENT_TYPE = "ai.retrieval.executed"
AI_MODEL_INVOKED_EVENT_TYPE = "ai.model.invoked"
AI_MODEL_OUTPUT_EVENT_TYPE = "ai.model.output"

RAG_INDEX_EVENT_TYPE = "atb.event.rag_index"
RAG_RETRIEVAL_EVENT_TYPE = "atb.event.rag_retrieval"

AI_ACTION_PRECOMMIT_EVENT_TYPE = "ai.action.precommit"
AI_ACTION_EXECUTED_EVENT_TYPE = "ai.action.executed"
AI_ACTION_COMMITTED_EVENT_TYPE = "ai.action.committed"

AI_HUMAN_APPROVAL_EVENT_TYPE = "ai.human.approval"
AI_OVERRIDE_REQUESTED_EVENT_TYPE = "ai.override.requested"

AI_JOB_SCHEDULED_EVENT_TYPE = "ai.job.scheduled"
AI_JOB_STARTED_EVENT_TYPE = "ai.job.started"
AI_JOB_STEP_EVENT_TYPE = "ai.job.step"
AI_JOB_COMPLETED_EVENT_TYPE = "ai.job.completed"

DATA_EXPORT_PRECOMMIT_EVENT_TYPE = "data.export.precommit"
DATA_EXPORT_EXECUTED_EVENT_TYPE = "data.export.executed"

TOOL_CALL = "atb.tool.call"
DATA_EXPORT = "atb.data.export"
HUMAN_OVERRIDE = "atb.human.override"
HUMAN_APPROVAL = "atb.human.approval"

__all__ = [
    "BUNDLE_MANIFEST_EVENT_TYPE",
    "BUNDLE_ANCHOR_EVENT_TYPE",
    "BUNDLE_SIGNATURE_EVENT_TYPE",
    "SNAPSHOT_EVENT_TYPE",
    "AI_REQUEST_RECEIVED_EVENT_TYPE",
    "AI_RESPONSE_SENT_EVENT_TYPE",
    "AI_LLM_CALL_EVENT_TYPE",
    "AI_TOOL_EXEC_EVENT_TYPE",
    "AI_CHAIN_RUN_EVENT_TYPE",
    "AI_POLICY_DECISION_EVENT_TYPE",
    "AI_RETRIEVAL_EXECUTED_EVENT_TYPE",
    "AI_MODEL_INVOKED_EVENT_TYPE",
    "AI_MODEL_OUTPUT_EVENT_TYPE",
    "RAG_INDEX_EVENT_TYPE",
    "RAG_RETRIEVAL_EVENT_TYPE",
    "AI_ACTION_PRECOMMIT_EVENT_TYPE",
    "AI_ACTION_EXECUTED_EVENT_TYPE",
    "AI_ACTION_COMMITTED_EVENT_TYPE",
    "AI_HUMAN_APPROVAL_EVENT_TYPE",
    "AI_OVERRIDE_REQUESTED_EVENT_TYPE",
    "AI_JOB_SCHEDULED_EVENT_TYPE",
    "AI_JOB_STARTED_EVENT_TYPE",
    "AI_JOB_STEP_EVENT_TYPE",
    "AI_JOB_COMPLETED_EVENT_TYPE",
    "DATA_EXPORT_PRECOMMIT_EVENT_TYPE",
    "DATA_EXPORT_EXECUTED_EVENT_TYPE",
    "TOOL_CALL",
    "DATA_EXPORT",
    "HUMAN_OVERRIDE",
    "HUMAN_APPROVAL",
]
