// Code generated by tools/eventgen; DO NOT EDIT.
// Source: schemas/event.v1.json event_types

/* eslint-disable */

export interface EventTypeSpec {
  readonly type: string;
  readonly description: string;
  readonly profiles: readonly string[];
  readonly criticality: string;
  readonly required_fields: readonly string[];
}

export const BUNDLE_MANIFEST = "atb.bundle.manifest" as const;
export const BUNDLE_MANIFEST_EVENT_TYPE = BUNDLE_MANIFEST;

export const BUNDLE_ANCHOR = "atb.bundle.anchor" as const;
export const BUNDLE_ANCHOR_EVENT_TYPE = BUNDLE_ANCHOR;

export const BUNDLE_SIGNATURE = "atb.bundle.signature" as const;
export const BUNDLE_SIGNATURE_EVENT_TYPE = BUNDLE_SIGNATURE;

export const SNAPSHOT = "atb.snapshot" as const;
export const SNAPSHOT_EVENT_TYPE = SNAPSHOT;

export const BUNDLE_PUSHED = "atb.bundle.pushed" as const;
export const BUNDLE_PUSHED_EVENT_TYPE = BUNDLE_PUSHED;

export const AI_REQUEST_RECEIVED = "ai.request.received" as const;
export const AI_REQUEST_RECEIVED_EVENT_TYPE = AI_REQUEST_RECEIVED;

export const AI_RESPONSE_SENT = "ai.response.sent" as const;
export const AI_RESPONSE_SENT_EVENT_TYPE = AI_RESPONSE_SENT;

export const AI_LLM_CALL = "ai.llm.call" as const;
export const AI_LLM_CALL_EVENT_TYPE = AI_LLM_CALL;

export const AI_TOOL_EXEC = "ai.tool.exec" as const;
export const AI_TOOL_EXEC_EVENT_TYPE = AI_TOOL_EXEC;

export const AI_CHAIN_RUN = "ai.chain.run" as const;
export const AI_CHAIN_RUN_EVENT_TYPE = AI_CHAIN_RUN;

export const AI_POLICY_DECISION = "ai.policy.decision" as const;
export const AI_POLICY_DECISION_EVENT_TYPE = AI_POLICY_DECISION;

export const AI_RETRIEVAL_EXECUTED = "ai.retrieval.executed" as const;
export const AI_RETRIEVAL_EXECUTED_EVENT_TYPE = AI_RETRIEVAL_EXECUTED;

export const AI_MODEL_INVOKED = "ai.model.invoked" as const;
export const AI_MODEL_INVOKED_EVENT_TYPE = AI_MODEL_INVOKED;

export const AI_MODEL_OUTPUT = "ai.model.output" as const;
export const AI_MODEL_OUTPUT_EVENT_TYPE = AI_MODEL_OUTPUT;

export const AI_ACTION_PRECOMMIT = "ai.action.precommit" as const;
export const AI_ACTION_PRECOMMIT_EVENT_TYPE = AI_ACTION_PRECOMMIT;

export const AI_ACTION_EXECUTED = "ai.action.executed" as const;
export const AI_ACTION_EXECUTED_EVENT_TYPE = AI_ACTION_EXECUTED;

export const AI_ACTION_COMMITTED = "ai.action.committed" as const;
export const AI_ACTION_COMMITTED_EVENT_TYPE = AI_ACTION_COMMITTED;

export const AI_HUMAN_APPROVAL = "ai.human.approval" as const;
export const AI_HUMAN_APPROVAL_EVENT_TYPE = AI_HUMAN_APPROVAL;

export const AI_OVERRIDE_REQUESTED = "ai.override.requested" as const;
export const AI_OVERRIDE_REQUESTED_EVENT_TYPE = AI_OVERRIDE_REQUESTED;

export const AI_JOB_SCHEDULED = "ai.job.scheduled" as const;
export const AI_JOB_SCHEDULED_EVENT_TYPE = AI_JOB_SCHEDULED;

export const AI_JOB_STARTED = "ai.job.started" as const;
export const AI_JOB_STARTED_EVENT_TYPE = AI_JOB_STARTED;

export const AI_JOB_STEP = "ai.job.step" as const;
export const AI_JOB_STEP_EVENT_TYPE = AI_JOB_STEP;

export const AI_JOB_COMPLETED = "ai.job.completed" as const;
export const AI_JOB_COMPLETED_EVENT_TYPE = AI_JOB_COMPLETED;

export const DATA_EXPORT_PRECOMMIT = "data.export.precommit" as const;
export const DATA_EXPORT_PRECOMMIT_EVENT_TYPE = DATA_EXPORT_PRECOMMIT;

export const DATA_EXPORT_EXECUTED = "data.export.executed" as const;
export const DATA_EXPORT_EXECUTED_EVENT_TYPE = DATA_EXPORT_EXECUTED;

export const DEV_SESSION = "dev.session" as const;
export const DEV_SESSION_EVENT_TYPE = DEV_SESSION;

export const SNAPSHOT_BUILD = "snapshot.build" as const;
export const SNAPSHOT_BUILD_EVENT_TYPE = SNAPSHOT_BUILD;

export const CORROBORATION_EXTERNAL = "atb.corroboration.external" as const;
export const CORROBORATION_EXTERNAL_EVENT_TYPE = CORROBORATION_EXTERNAL;

export const RAG_INDEX = "atb.event.rag_index" as const;
export const RAG_INDEX_EVENT_TYPE = RAG_INDEX;

export const RAG_RETRIEVAL = "atb.event.rag_retrieval" as const;
export const RAG_RETRIEVAL_EVENT_TYPE = RAG_RETRIEVAL;

export const TOOL_CALL = "atb.tool.call" as const;
export const TOOL_CALL_EVENT_TYPE = TOOL_CALL;

export const DATA_EXPORT = "atb.data.export" as const;
export const DATA_EXPORT_EVENT_TYPE = DATA_EXPORT;

export const HUMAN_OVERRIDE = "atb.human.override" as const;
export const HUMAN_OVERRIDE_EVENT_TYPE = HUMAN_OVERRIDE;

export const HUMAN_APPROVAL = "atb.human.approval" as const;
export const HUMAN_APPROVAL_EVENT_TYPE = HUMAN_APPROVAL;

export const SESSION_CLOSE = "atb.session.close" as const;
export const SESSION_CLOSE_EVENT_TYPE = SESSION_CLOSE;

export const EXCHANGE_COMPLETE = "atb.exchange.complete" as const;
export const EXCHANGE_COMPLETE_EVENT_TYPE = EXCHANGE_COMPLETE;

export const EVENT_TYPE_REGISTRY = [
  {
    type: BUNDLE_MANIFEST,
    description: "Bundle manifest (seq 0, always first in a new bundle)",
    profiles: ["atb.profile.privileged_tool_action", "atb.profile.rag_answer", "atb.profile.data_export", "atb.profile.policy_decision", "atb.profile.human_override", "atb.profile.background_automation"],
    criticality: "critical",
    required_fields: ["version", "created_at", "bundle_id"],
  },
  {
    type: BUNDLE_ANCHOR,
    description: "RFC 3161 TSA timestamp anchor",
    profiles: ["all"],
    criticality: "required",
    required_fields: ["tsa_url", "bundle_hash", "tsr_hash", "tsr_der", "certified_time"],
  },
  {
    type: BUNDLE_SIGNATURE,
    description: "Ed25519 bundle signature",
    profiles: ["all"],
    criticality: "required",
    required_fields: ["bundle_hash", "signature", "pubkey"],
  },
  {
    type: SNAPSHOT,
    description: "Bundle snapshot marker",
    profiles: [],
    criticality: "informational",
    required_fields: ["name", "bundle_hash", "record_count", "snapshot_at"],
  },
  {
    type: BUNDLE_PUSHED,
    description: "Bundle pushed to remote WORM target (atb push)",
    profiles: [],
    criticality: "informational",
    required_fields: [],
  },
  {
    type: AI_REQUEST_RECEIVED,
    description: "AI request received at app boundary",
    profiles: ["atb.profile.rag_answer", "atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.policy_decision", "atb.profile.human_override"],
    criticality: "critical",
    required_fields: ["request_id", "actor_id_hash", "purpose_tag"],
  },
  {
    type: AI_RESPONSE_SENT,
    description: "AI response sent from app boundary",
    profiles: ["atb.profile.rag_answer"],
    criticality: "required",
    required_fields: ["request_id", "output_digest"],
  },
  {
    type: AI_LLM_CALL,
    description: "Canonical LLM lifecycle event for integrations",
    profiles: [],
    criticality: "informational",
    required_fields: [],
  },
  {
    type: AI_TOOL_EXEC,
    description: "Canonical tool execution lifecycle event for integrations",
    profiles: [],
    criticality: "informational",
    required_fields: [],
  },
  {
    type: AI_CHAIN_RUN,
    description: "Canonical chain or step lifecycle event for integrations",
    profiles: [],
    criticality: "informational",
    required_fields: [],
  },
  {
    type: AI_POLICY_DECISION,
    description: "Policy engine decision (allow/deny)",
    profiles: ["atb.profile.privileged_tool_action", "atb.profile.rag_answer", "atb.profile.data_export", "atb.profile.policy_decision"],
    criticality: "critical",
    required_fields: [],
  },
  {
    type: AI_RETRIEVAL_EXECUTED,
    description: "Retrieval step executed (RAG)",
    profiles: ["atb.profile.rag_answer"],
    criticality: "required",
    required_fields: [],
  },
  {
    type: AI_MODEL_INVOKED,
    description: "LLM invocation sent",
    profiles: ["atb.profile.rag_answer"],
    criticality: "critical",
    required_fields: ["model_provider", "model_id", "model_parameters_digest", "prompt_digest"],
  },
  {
    type: AI_MODEL_OUTPUT,
    description: "LLM output received",
    profiles: ["atb.profile.rag_answer"],
    criticality: "critical",
    required_fields: ["output_digest", "output_format"],
  },
  {
    type: AI_ACTION_PRECOMMIT,
    description: "Pre-commit record for a gated privileged action",
    profiles: ["atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.policy_decision", "atb.profile.human_override"],
    criticality: "critical",
    required_fields: ["action_id", "action_type", "action_parameters_digest", "target_resource_id", "intended_effect"],
  },
  {
    type: AI_ACTION_EXECUTED,
    description: "Privileged action executed through gate",
    profiles: ["atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.human_override"],
    criticality: "critical",
    required_fields: ["action_id", "execution_outcome", "tool_receipt_digest"],
  },
  {
    type: AI_ACTION_COMMITTED,
    description: "Privileged action committed to sink",
    profiles: ["atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.human_override"],
    criticality: "critical",
    required_fields: [],
  },
  {
    type: AI_HUMAN_APPROVAL,
    description: "Human approval of an action or override",
    profiles: ["atb.profile.privileged_tool_action", "atb.profile.data_export", "atb.profile.human_override"],
    criticality: "required",
    required_fields: [],
  },
  {
    type: AI_OVERRIDE_REQUESTED,
    description: "Human override requested",
    profiles: [],
    criticality: "critical",
    required_fields: [],
  },
  {
    type: AI_JOB_SCHEDULED,
    description: "Background job scheduled",
    profiles: ["atb.profile.background_automation"],
    criticality: "critical",
    required_fields: [],
  },
  {
    type: AI_JOB_STARTED,
    description: "Background job started by worker",
    profiles: ["atb.profile.background_automation"],
    criticality: "critical",
    required_fields: [],
  },
  {
    type: AI_JOB_STEP,
    description: "Individual step within a background job",
    profiles: ["atb.profile.background_automation"],
    criticality: "critical",
    required_fields: [],
  },
  {
    type: AI_JOB_COMPLETED,
    description: "Background job completed",
    profiles: ["atb.profile.background_automation"],
    criticality: "critical",
    required_fields: [],
  },
  {
    type: DATA_EXPORT_PRECOMMIT,
    description: "Pre-commit record for a data export",
    profiles: ["atb.profile.data_export"],
    criticality: "critical",
    required_fields: [],
  },
  {
    type: DATA_EXPORT_EXECUTED,
    description: "Data export executed to sink",
    profiles: ["atb.profile.data_export"],
    criticality: "critical",
    required_fields: [],
  },
  {
    type: DEV_SESSION,
    description: "Developer session marker (tooling use)",
    profiles: [],
    criticality: "informational",
    required_fields: [],
  },
  {
    type: SNAPSHOT_BUILD,
    description: "Build snapshot (tooling use)",
    profiles: [],
    criticality: "informational",
    required_fields: [],
  },
  {
    type: CORROBORATION_EXTERNAL,
    description: "External corroboration record (adapter-retrieved evidence)",
    profiles: [],
    criticality: "informational",
    required_fields: [],
  },
  {
    type: RAG_INDEX,
    description: "PageIndex document tree build record (index_hash, node_count)",
    profiles: ["atb.profile.rag_answer"],
    criticality: "required",
    required_fields: [],
  },
  {
    type: RAG_RETRIEVAL,
    description: "PageIndex reasoning-based retrieval result (node_id, page_start/end)",
    profiles: ["atb.profile.rag_answer"],
    criticality: "required",
    required_fields: [],
  },
  {
    type: TOOL_CALL,
    description: "Tool invocation recorded for session oversight",
    profiles: [],
    criticality: "required",
    required_fields: ["session_id", "tool_name"],
  },
  {
    type: DATA_EXPORT,
    description: "Data export outside session boundary",
    profiles: [],
    criticality: "required",
    required_fields: ["session_id", "export_target"],
  },
  {
    type: HUMAN_OVERRIDE,
    description: "Human operator overrode an AI-recommended action",
    profiles: [],
    criticality: "required",
    required_fields: ["session_id", "override_reason"],
  },
  {
    type: HUMAN_APPROVAL,
    description: "Human operator approved a pending action",
    profiles: [],
    criticality: "required",
    required_fields: ["session_id", "approved_action_id"],
  },
  {
    type: SESSION_CLOSE,
    description: "Capture session closed (proxy-internal lifecycle marker)",
    profiles: [],
    criticality: "informational",
    required_fields: ["session_id", "actor_id"],
  },
  {
    type: EXCHANGE_COMPLETE,
    description: "Request/response exchange completed within a capture session (proxy-internal)",
    profiles: [],
    criticality: "informational",
    required_fields: ["session_id", "exchange_id", "request_event_id"],
  },
] as const satisfies readonly EventTypeSpec[];

export const EVENT_TYPE_REQUIRED_FIELDS = {
  [BUNDLE_MANIFEST]: ["version", "created_at", "bundle_id"],
  [BUNDLE_ANCHOR]: ["tsa_url", "bundle_hash", "tsr_hash", "tsr_der", "certified_time"],
  [BUNDLE_SIGNATURE]: ["bundle_hash", "signature", "pubkey"],
  [SNAPSHOT]: ["name", "bundle_hash", "record_count", "snapshot_at"],
  [BUNDLE_PUSHED]: [],
  [AI_REQUEST_RECEIVED]: ["request_id", "actor_id_hash", "purpose_tag"],
  [AI_RESPONSE_SENT]: ["request_id", "output_digest"],
  [AI_LLM_CALL]: [],
  [AI_TOOL_EXEC]: [],
  [AI_CHAIN_RUN]: [],
  [AI_POLICY_DECISION]: [],
  [AI_RETRIEVAL_EXECUTED]: [],
  [AI_MODEL_INVOKED]: ["model_provider", "model_id", "model_parameters_digest", "prompt_digest"],
  [AI_MODEL_OUTPUT]: ["output_digest", "output_format"],
  [AI_ACTION_PRECOMMIT]: ["action_id", "action_type", "action_parameters_digest", "target_resource_id", "intended_effect"],
  [AI_ACTION_EXECUTED]: ["action_id", "execution_outcome", "tool_receipt_digest"],
  [AI_ACTION_COMMITTED]: [],
  [AI_HUMAN_APPROVAL]: [],
  [AI_OVERRIDE_REQUESTED]: [],
  [AI_JOB_SCHEDULED]: [],
  [AI_JOB_STARTED]: [],
  [AI_JOB_STEP]: [],
  [AI_JOB_COMPLETED]: [],
  [DATA_EXPORT_PRECOMMIT]: [],
  [DATA_EXPORT_EXECUTED]: [],
  [DEV_SESSION]: [],
  [SNAPSHOT_BUILD]: [],
  [CORROBORATION_EXTERNAL]: [],
  [RAG_INDEX]: [],
  [RAG_RETRIEVAL]: [],
  [TOOL_CALL]: ["session_id", "tool_name"],
  [DATA_EXPORT]: ["session_id", "export_target"],
  [HUMAN_OVERRIDE]: ["session_id", "override_reason"],
  [HUMAN_APPROVAL]: ["session_id", "approved_action_id"],
  [SESSION_CLOSE]: ["session_id", "actor_id"],
  [EXCHANGE_COMPLETE]: ["session_id", "exchange_id", "request_event_id"],
} as const;
