"use client";

import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { ArrowRight, Search } from "lucide-react";
import { EmptyState, StatusBadge, SurfaceHeader } from "./ui/investigation";
import type { InvestigationFinding, InvestigationOverview, TimelineEvent } from "@/lib/types";

export const actionClass = "inline-flex items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-sm hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:opacity-50";
export const rowClass = "w-full border-b border-border px-4 py-3 text-left text-sm transition-colors hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring";

export function SplitWorkspace({ list, inspector }: { list: ReactNode; inspector: ReactNode }) {
  return <div className="grid min-w-0 items-start gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(22rem,0.9fr)]"><div className="min-w-0">{list}</div><div aria-label="Selection inspector" className="min-w-0 xl:sticky xl:top-4">{inspector}</div></div>;
}

export function FilterBar({ search, setSearch, label, count, children }: { search: string; setSearch: (value: string) => void; label: string; count: string; children?: ReactNode }) {
  return <div className="flex flex-wrap items-center gap-3 rounded-md border border-border bg-surface-1 p-3"><label className="flex min-w-40 flex-1 items-center gap-2"><Search className="h-4 w-4 shrink-0 text-muted-foreground" aria-hidden="true"/><input aria-label={label} placeholder={label} value={search} onChange={event => setSearch(event.target.value)} className="min-w-0 w-full rounded-sm bg-transparent text-sm outline-none placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring"/></label>{children}<span role="status" className="text-xs text-muted-foreground">{count}</span>{search && <button type="button" onClick={() => setSearch("")} className="rounded-sm text-xs text-primary focus-visible:ring-2 focus-visible:ring-ring">Clear search</button>}</div>;
}

export function coverageLabel(valid: boolean, profile: InvestigationOverview["profile"]) {
  if (!valid) return "Untrusted";
  if (!profile?.coverage_grade?.trim()) return "Not assessed";
  return typeof profile.coverage_score === "number" ? `${Math.round(profile.coverage_score * 100)}%` : profile.coverage_grade;
}

export function FindingDetail({ finding, openEvidence, openTimeline }: { finding: InvestigationFinding; openEvidence: (seq: number) => void; openTimeline: (seq: number) => void }) {
  return <article className="rounded-lg border border-border bg-card">
    <header className="space-y-3 border-b border-border p-4"><StatusBadge tone={finding.severity === "critical" || finding.severity === "high" ? "warning" : "unknown"}>{finding.severity || "inconclusive"}</StatusBadge><h3 className="text-lg font-semibold">{finding.title}</h3><p className="text-sm leading-6 text-secondary-foreground">{finding.detail}</p></header>
    <dl className="space-y-5 p-4 text-sm"><div><dt className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">ATB can conclude</dt><dd className="mt-2 leading-6">{finding.what_atb_can_conclude}</dd></div><div><dt className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">ATB cannot conclude</dt><dd className="mt-2 leading-6 text-secondary-foreground">{finding.what_atb_cannot_conclude}</dd></div><div><dt className="text-xs text-muted-foreground">Basis</dt><dd className="mt-1 break-words">{finding.basis}</dd></div></dl>
    <div className="border-t border-border p-4"><h4 className="text-sm font-medium">Supporting events <span className="text-muted-foreground">({finding.event_seqs.length})</span></h4>{finding.event_seqs.length ? <ul className="mt-2 divide-y divide-border">{finding.event_seqs.map(seq => <li key={seq} className="flex flex-wrap items-center justify-between gap-2 py-2"><button className="rounded-sm font-mono text-sm text-primary focus-visible:ring-2 focus-visible:ring-ring" onClick={() => openEvidence(seq)}>#{seq}</button><button className="rounded-sm text-xs text-primary focus-visible:ring-2 focus-visible:ring-ring" onClick={() => openTimeline(seq)}>Inspect in timeline →</button></li>)}</ul> : <p className="mt-2 text-sm text-muted-foreground">No exact event references were supplied by this finding.</p>}</div>
  </article>;
}

export function FindingsSurface({ findings, selected, select, openEvidence, openTimeline }: { findings: InvestigationFinding[]; selected: number; select: (index: number) => void; openEvidence: (seq: number) => void; openTimeline: (seq: number) => void }) {
  const [search, setSearch] = useState("");
  const [severity, setSeverity] = useState("");
  const rows = findings.map((finding, index) => ({ finding, index })).filter(({ finding }) => (!severity || finding.severity === severity) && `${finding.title} ${finding.detail} ${finding.flag}`.toLowerCase().includes(search.toLowerCase()));
  const active = findings[selected] ?? findings[0];
  return <section className="space-y-4"><SurfaceHeader title="Findings" description="Bounded conclusions and their supporting records."/><FilterBar search={search} setSearch={setSearch} label="Search findings" count={`${rows.length} of ${findings.length}`}><select aria-label="Finding severity" value={severity} onChange={event => setSeverity(event.target.value)} className="rounded border border-border bg-card p-1 text-sm"><option value="">All severities</option>{Array.from(new Set(findings.map(f => f.severity))).sort().map(value => <option key={value}>{value}</option>)}</select></FilterBar>
    {findings.length === 0 ? <EmptyState title="No findings in recorded evidence">No findings. This does not prove complete capture or universal absence.</EmptyState> : <SplitWorkspace list={<div className="overflow-hidden rounded-lg border border-border bg-card">{rows.length === 0 ? <EmptyState title="No matching findings">Change or clear the filters to inspect other findings.</EmptyState> : rows.map(({ finding, index }) => <button key={`${finding.flag}-${index}`} onClick={() => select(index)} aria-pressed={index === selected} className={`${rowClass} ${index === selected ? "border-l-2 border-l-primary bg-primary/10" : ""}`}><div className="flex items-center justify-between gap-3"><span className="font-medium">{finding.title}</span><span className="text-xs text-muted-foreground">{finding.severity}</span></div><p className="mt-2 line-clamp-2 text-secondary-foreground">{finding.detail}</p><p className="mt-2 text-xs text-muted-foreground">{finding.event_seqs.length} supporting events{finding.session_id ? ` · ${finding.session_id}` : ""}</p></button>)}</div>} inspector={active && <FindingDetail finding={active} openEvidence={openEvidence} openTimeline={openTimeline}/>}/>}</section>;
}

export function RecordSurface({ timeline, selectedSeq, select, inspector, evidence }: { timeline: TimelineEvent[]; selectedSeq: number | null; select: (seq: number) => void; inspector: ReactNode; evidence: boolean }) {
  const [search, setSearch] = useState("");
  const [type, setType] = useState("");
  const rowRefs = useRef(new Map<number, HTMLButtonElement>());
  const rows = useMemo(() => [...timeline].sort((left, right) => left.seq - right.seq).filter(event => (!type || event.type === type) && `${event.seq} ${event.type} ${event.label} ${event.hash}`.toLowerCase().includes(search.toLowerCase())), [timeline, type, search]);
  useEffect(() => {
    if (selectedSeq !== null) rowRefs.current.get(selectedSeq)?.focus();
  }, [selectedSeq]);
  return <section className="space-y-4"><SurfaceHeader title={evidence ? "Exact records" : "Timeline"} description={evidence ? "Source records, hashes and audited field inspection." : "Recorded sequence is authoritative. Timestamps appear only when recorded."}/><FilterBar search={search} setSearch={setSearch} label="Search event identity, type or hash" count={`${rows.length} of ${timeline.length} records`}><select aria-label="Event type" value={type} onChange={event => setType(event.target.value)} className="max-w-64 rounded border border-border bg-card p-1 text-sm"><option value="">All event types</option>{Array.from(new Set(timeline.map(e => e.type))).sort().map(value => <option key={value}>{value}</option>)}</select></FilterBar><SplitWorkspace list={<div className="overflow-hidden rounded-lg border border-border bg-card"><div className="flex justify-between border-b border-border bg-surface-1 px-4 py-2 text-xs text-muted-foreground"><span>Sequence / Event</span><span>Recorded time</span></div>{rows.map(event => <button key={event.seq} ref={node => { if (node) rowRefs.current.set(event.seq, node); else rowRefs.current.delete(event.seq); }} onClick={() => select(event.seq)} aria-pressed={event.seq === selectedSeq} className={`${rowClass} ${event.seq === selectedSeq ? "border-l-2 border-l-primary bg-primary/10" : ""}`}><div className="flex items-start gap-3"><span className="mt-0.5 w-10 shrink-0 font-mono text-xs text-muted-foreground">#{event.seq}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline justify-between gap-2"><span className="font-medium">{event.label}</span><span className="font-mono text-xs text-muted-foreground">{event.timestamp || "time unavailable"}</span></div><p className="mt-1 break-all font-mono text-xs text-muted-foreground">{event.type}</p><p className="mt-2 truncate font-mono text-xs text-muted-foreground" title={event.hash}>{event.hash}</p></div></div></button>)}{rows.length === 0 && <EmptyState title={timeline.length ? "No matching records" : "No recorded events"}>{timeline.length ? "Change or clear the filters. Search covers record identity and metadata." : "No event-derived timeline is available for this bundle."}</EmptyState>}</div>} inspector={inspector}/></section>;
}

export function IncidentSurface({ overview, findings, timeline, findingsState, openFindings, openEvidence, openTimeline, openTrust }: { overview: InvestigationOverview; findings: InvestigationFinding[]; timeline: TimelineEvent[]; findingsState?: ReactNode; openFindings: (index: number) => void; openEvidence: (seq: number) => void; openTimeline: (seq?: number) => void; openTrust: () => void }) {
  const timestamps = timeline.map(e => e.timestamp).filter((value): value is string => Boolean(value)).sort();
  return <section className="space-y-5" aria-labelledby="incident-heading"><header className="border-b border-border pb-5"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">What happened?</p><h2 id="incident-heading" className="mt-2 max-w-4xl text-2xl font-semibold leading-9">{overview.summary}</h2><p className="mt-2 text-sm text-muted-foreground">{overview.event_count} recorded events · conclusions are bounded to this bundle</p></header>
  <dl className="grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 xl:grid-cols-4">{[["Profile", overview.profile?.profile_id || "Not selected"], ["Evidence coverage", coverageLabel(overview.integrity_valid, overview.profile)], ["Important findings", String(overview.finding_count)], ["Custody", overview.custody_state]].map(([label, value]) => <div key={label} className="bg-card p-4"><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-2 break-words text-sm font-medium">{value}</dd></div>)}</dl>
  <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(18rem,1fr)]"><div className="space-y-3"><div className="flex items-center justify-between"><h3 className="font-semibold">Priority findings</h3><button onClick={() => openFindings(0)} className="rounded-sm text-sm text-primary focus-visible:ring-2 focus-visible:ring-ring">View all →</button></div>{findingsState || (overview.integrity_valid ? findings.length ? <div className="overflow-hidden rounded-lg border border-border bg-card">{findings.slice(0, 3).map((finding, index) => <article key={`${finding.flag}-${index}`} className="border-b border-border p-4 last:border-0"><button className="rounded-sm text-left font-medium text-primary focus-visible:ring-2 focus-visible:ring-ring" onClick={() => openFindings(index)}>{finding.title}</button><p className="mt-2 text-sm leading-6 text-secondary-foreground">{finding.detail}</p><div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground"><span>{finding.severity} · Supporting events</span>{finding.event_seqs.map(seq => <button key={seq} className="rounded-sm font-mono text-primary focus-visible:ring-2 focus-visible:ring-ring" onClick={() => openEvidence(seq)}>#{seq}</button>)}</div></article>)}</div> : <EmptyState title="No findings in recorded evidence">No findings. This does not prove complete capture or universal absence.</EmptyState> : <EmptyState title="Investigation conclusions blocked">Record integrity must be established before findings can be trusted.</EmptyState>)}
  <div className="rounded-lg border border-border bg-card p-4"><h3 className="text-sm font-semibold">Recorded time range</h3><p className="mt-2 break-words font-mono text-xs leading-6 text-secondary-foreground">{timestamps.length ? `${timestamps[0]} → ${timestamps[timestamps.length - 1]}` : "Time unavailable"}</p>{timestamps.length > 0 && timestamps.length < timeline.length && <p className="mt-2 text-xs text-muted-foreground">Some records have no timestamp. Sequence remains available.</p>}</div></div>
  <div className="space-y-4"><div className="rounded-lg border border-border bg-card p-4"><h3 className="text-sm font-semibold">What is known</h3><p className="mt-2 text-sm leading-6 text-secondary-foreground">{overview.integrity_valid ? "The presented records match their hash chain and recorded order." : "The presented records do not match their hash chain."}</p><h3 className="mt-5 text-sm font-semibold">What is not known</h3><p className="mt-2 text-sm leading-6 text-secondary-foreground">Integrity does not establish complete capture, real-world truth, or independent custody.</p>{overview.profile?.critical_failures.map((gap, index) => <p key={index} className="mt-3 border-l-2 border-warning pl-3 text-sm leading-6">{gap.detail}</p>)}</div><div className="rounded-lg border border-border bg-surface-1 p-4"><h3 className="mb-3 text-sm font-semibold">Inspect next</h3><div className="flex flex-col gap-2"><button className={actionClass} onClick={() => openTimeline()}>Follow the recorded timeline <ArrowRight className="ml-auto h-4 w-4"/></button><button className={actionClass} onClick={openTrust}>Inspect trust and evidence gaps <ArrowRight className="ml-auto h-4 w-4"/></button></div></div></div></div></section>;
}
