// SPDX-License-Identifier: MIT
// eventgen generates language event-taxonomy bindings from schemas/event.v1.json.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type EventTypeSpec struct {
	Type           string   `json:"type"`
	Description    string   `json:"description"`
	Profiles       []string `json:"profiles"`
	Criticality    string   `json:"criticality"`
	RequiredFields []string `json:"required_fields"`
}

type schemaFile struct {
	EventTypes []EventTypeSpec `json:"event_types"`
}

func main() {
	schemaPath := flag.String("schema", "", "path to schemas/event.v1.json")
	flag.Parse()

	if strings.TrimSpace(*schemaPath) == "" {
		fatalf("-schema is required")
	}

	specs, repoRoot, err := loadSpecs(*schemaPath)
	if err != nil {
		fatalf("%v", err)
	}

	outputs := []struct {
		path   string
		render func([]EventTypeSpec) ([]byte, error)
	}{
		{
			path:   "internal/event/types_generated.go",
			render: renderGo,
		},
		{
			path:   "sdk/python/atb/event_types_generated.py",
			render: renderPython,
		},
		{
			path:   "sdk/typescript/src/eventTypes_generated.ts",
			render: renderTypeScript,
		},
	}

	for _, output := range outputs {
		data, err := output.render(specs)
		if err != nil {
			fatalf("render %s: %v", output.path, err)
		}
		path := filepath.Join(repoRoot, output.path)
		if err := writeAtomic(path, data); err != nil {
			fatalf("write %s: %v", path, err)
		}
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "eventgen: "+format+"\n", args...)
	os.Exit(1)
}

func loadSpecs(schemaPath string) ([]EventTypeSpec, string, error) {
	absSchema, err := filepath.Abs(schemaPath)
	if err != nil {
		return nil, "", fmt.Errorf("resolve schema path: %w", err)
	}

	raw, err := os.ReadFile(absSchema)
	if err != nil {
		return nil, "", fmt.Errorf("read schema: %w", err)
	}

	var schema schemaFile
	if err := json.Unmarshal(raw, &schema); err != nil {
		return nil, "", fmt.Errorf("parse schema: %w", err)
	}
	if len(schema.EventTypes) == 0 {
		return nil, "", fmt.Errorf("schema has no event_types entries")
	}

	seen := map[string]struct{}{}
	for i := range schema.EventTypes {
		spec := &schema.EventTypes[i]
		spec.Type = strings.TrimSpace(spec.Type)
		spec.Description = strings.TrimSpace(spec.Description)
		spec.Criticality = strings.TrimSpace(spec.Criticality)
		if spec.Type == "" {
			return nil, "", fmt.Errorf("event_types[%d]: type is required", i)
		}
		if spec.Description == "" {
			return nil, "", fmt.Errorf("event_types[%d] %q: description is required", i, spec.Type)
		}
		if spec.Criticality == "" {
			return nil, "", fmt.Errorf("event_types[%d] %q: criticality is required", i, spec.Type)
		}
		if _, ok := seen[spec.Type]; ok {
			return nil, "", fmt.Errorf("event_types[%d] %q: duplicate type", i, spec.Type)
		}
		seen[spec.Type] = struct{}{}
		if spec.Profiles == nil {
			spec.Profiles = []string{}
		}
		if spec.RequiredFields == nil {
			spec.RequiredFields = []string{}
		}
	}

	repoRoot := filepath.Dir(filepath.Dir(absSchema))
	return schema.EventTypes, repoRoot, nil
}

func renderGo(specs []EventTypeSpec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/eventgen; DO NOT EDIT.\n")
	buf.WriteString("// Source: schemas/event.v1.json event_types\n\n")
	buf.WriteString("package event\n\n")

	buf.WriteString("const (\n")
	for _, spec := range specs {
		fmt.Fprintf(&buf, "\t// %s is %s.\n", goConstName(spec.Type), strconv.Quote(spec.Type))
		fmt.Fprintf(&buf, "\t%s = %s\n", goConstName(spec.Type), strconv.Quote(spec.Type))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("// EventTypeSpecGenerated mirrors the schema event_types metadata block.\n")
	buf.WriteString("type EventTypeSpecGenerated struct {\n")
	buf.WriteString("\tType string `json:\"type\"`\n")
	buf.WriteString("\tDescription string `json:\"description\"`\n")
	buf.WriteString("\tProfiles []string `json:\"profiles\"`\n")
	buf.WriteString("\tCriticality string `json:\"criticality\"`\n")
	buf.WriteString("\tRequiredFields []string `json:\"required_fields\"`\n")
	buf.WriteString("}\n\n")

	buf.WriteString("// EventTypesGenerated is generated from schemas/event.v1.json event_types.\n")
	buf.WriteString("var EventTypesGenerated = []EventTypeSpecGenerated{\n")
	for _, spec := range specs {
		fmt.Fprintf(
			&buf,
			"\t{Type: %s, Description: %s, Profiles: %s, Criticality: %s, RequiredFields: %s},\n",
			goConstName(spec.Type),
			strconv.Quote(spec.Description),
			goStringSlice(spec.Profiles),
			strconv.Quote(spec.Criticality),
			goStringSlice(spec.RequiredFields),
		)
	}
	buf.WriteString("}\n\n")

	buf.WriteString("// RegistryGenerated is the EventInfo view generated from schemas/event.v1.json event_types.\n")
	buf.WriteString("var RegistryGenerated = []EventInfo{\n")
	for _, spec := range specs {
		fmt.Fprintf(
			&buf,
			"\t{%s, %s, %s, %s},\n",
			goConstName(spec.Type),
			strconv.Quote(spec.Description),
			strconv.Quote(strings.Join(spec.Profiles, ",")),
			strconv.Quote(spec.Criticality),
		)
	}
	buf.WriteString("}\n\n")

	buf.WriteString("// RequiredFieldsGenerated maps each event type to schema-declared required data fields.\n")
	buf.WriteString("var RequiredFieldsGenerated = map[string][]string{\n")
	for _, spec := range specs {
		fmt.Fprintf(&buf, "\t%s: %s,\n", goConstName(spec.Type), goStringSlice(spec.RequiredFields))
	}
	buf.WriteString("}\n")

	return format.Source(buf.Bytes())
}

func renderPython(specs []EventTypeSpec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("# Code generated by tools/eventgen; DO NOT EDIT.\n")
	buf.WriteString("# Source: schemas/event.v1.json event_types\n")
	buf.WriteString("# ruff: noqa\n")
	buf.WriteString("from __future__ import annotations\n\n")
	buf.WriteString("from typing import Final, TypedDict\n\n\n")
	buf.WriteString("class EventTypeSpec(TypedDict):\n")
	buf.WriteString("    type: str\n")
	buf.WriteString("    description: str\n")
	buf.WriteString("    profiles: list[str]\n")
	buf.WriteString("    criticality: str\n")
	buf.WriteString("    required_fields: list[str]\n\n\n")

	for _, spec := range specs {
		name := sdkConstName(spec.Type)
		fmt.Fprintf(&buf, "%s: Final = %s\n", name, jsonString(spec.Type))
		fmt.Fprintf(&buf, "%s_EVENT_TYPE: Final = %s\n\n", name, name)
	}

	buf.WriteString("EVENT_TYPE_REGISTRY: list[EventTypeSpec] = [\n")
	for _, spec := range specs {
		buf.WriteString("    {\n")
		fmt.Fprintf(&buf, "        \"type\": %s,\n", sdkConstName(spec.Type))
		fmt.Fprintf(&buf, "        \"description\": %s,\n", jsonString(spec.Description))
		fmt.Fprintf(&buf, "        \"profiles\": %s,\n", pyStringList(spec.Profiles))
		fmt.Fprintf(&buf, "        \"criticality\": %s,\n", jsonString(spec.Criticality))
		fmt.Fprintf(&buf, "        \"required_fields\": %s,\n", pyStringList(spec.RequiredFields))
		buf.WriteString("    },\n")
	}
	buf.WriteString("]\n\n")

	buf.WriteString("EVENT_TYPE_REQUIRED_FIELDS: dict[str, list[str]] = {\n")
	for _, spec := range specs {
		fmt.Fprintf(&buf, "    %s: %s,\n", sdkConstName(spec.Type), pyStringList(spec.RequiredFields))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("__all__ = [\n")
	buf.WriteString("    \"EventTypeSpec\",\n")
	buf.WriteString("    \"EVENT_TYPE_REGISTRY\",\n")
	buf.WriteString("    \"EVENT_TYPE_REQUIRED_FIELDS\",\n")
	for _, spec := range specs {
		name := sdkConstName(spec.Type)
		fmt.Fprintf(&buf, "    %s,\n", jsonString(name))
		fmt.Fprintf(&buf, "    %s,\n", jsonString(name+"_EVENT_TYPE"))
	}
	buf.WriteString("]\n")

	return buf.Bytes(), nil
}

func renderTypeScript(specs []EventTypeSpec) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/eventgen; DO NOT EDIT.\n")
	buf.WriteString("// Source: schemas/event.v1.json event_types\n\n")
	buf.WriteString("/* eslint-disable */\n\n")
	buf.WriteString("export interface EventTypeSpec {\n")
	buf.WriteString("  readonly type: string;\n")
	buf.WriteString("  readonly description: string;\n")
	buf.WriteString("  readonly profiles: readonly string[];\n")
	buf.WriteString("  readonly criticality: string;\n")
	buf.WriteString("  readonly required_fields: readonly string[];\n")
	buf.WriteString("}\n\n")

	for _, spec := range specs {
		name := sdkConstName(spec.Type)
		fmt.Fprintf(&buf, "export const %s = %s as const;\n", name, jsonString(spec.Type))
		fmt.Fprintf(&buf, "export const %s_EVENT_TYPE = %s;\n\n", name, name)
	}

	buf.WriteString("export const EVENT_TYPE_REGISTRY = [\n")
	for _, spec := range specs {
		buf.WriteString("  {\n")
		fmt.Fprintf(&buf, "    type: %s,\n", sdkConstName(spec.Type))
		fmt.Fprintf(&buf, "    description: %s,\n", jsonString(spec.Description))
		fmt.Fprintf(&buf, "    profiles: %s,\n", tsStringArray(spec.Profiles))
		fmt.Fprintf(&buf, "    criticality: %s,\n", jsonString(spec.Criticality))
		fmt.Fprintf(&buf, "    required_fields: %s,\n", tsStringArray(spec.RequiredFields))
		buf.WriteString("  },\n")
	}
	buf.WriteString("] as const satisfies readonly EventTypeSpec[];\n\n")

	buf.WriteString("export const EVENT_TYPE_REQUIRED_FIELDS = {\n")
	for _, spec := range specs {
		fmt.Fprintf(
			&buf,
			"  [%s]: %s,\n",
			sdkConstName(spec.Type),
			tsStringArray(spec.RequiredFields),
		)
	}
	buf.WriteString("} as const;\n")

	return buf.Bytes(), nil
}

func writeAtomic(path string, data []byte) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(dir, ".eventgen-*")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmpName, 0o644); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

func goConstName(eventType string) string {
	return "Type" + pascalName(constParts(eventType))
}

func sdkConstName(eventType string) string {
	parts := constParts(eventType)
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		out = append(out, strings.ToUpper(part))
	}
	return strings.Join(out, "_")
}

func constParts(eventType string) []string {
	switch {
	case strings.HasPrefix(eventType, "atb.bundle."):
		return append([]string{"bundle"}, splitName(strings.TrimPrefix(eventType, "atb.bundle."))...)
	case eventType == "atb.snapshot":
		return []string{"snapshot"}
	case strings.HasPrefix(eventType, "atb.event."):
		return splitName(strings.TrimPrefix(eventType, "atb.event."))
	case strings.HasPrefix(eventType, "atb.corroboration."):
		return append([]string{"corroboration"}, splitName(strings.TrimPrefix(eventType, "atb.corroboration."))...)
	case strings.HasPrefix(eventType, "ai."):
		return append([]string{"ai"}, splitName(strings.TrimPrefix(eventType, "ai."))...)
	default:
		return splitName(eventType)
	}
}

func splitName(s string) []string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '.' || r == '_' || r == '-'
	})
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		if part == "" {
			continue
		}
		out = append(out, strings.ToLower(part))
	}
	return out
}

func pascalName(parts []string) string {
	var b strings.Builder
	for _, part := range parts {
		if acronym, ok := acronymFor(part); ok {
			b.WriteString(acronym)
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			b.WriteString(part[1:])
		}
	}
	return b.String()
}

func acronymFor(s string) (string, bool) {
	acronyms := map[string]string{
		"ai":  "AI",
		"atb": "ATB",
		"id":  "ID",
		"llm": "LLM",
		"rag": "RAG",
		"tsa": "TSA",
		"url": "URL",
	}
	value, ok := acronyms[s]
	return value, ok
}

func goStringSlice(values []string) string {
	if len(values) == 0 {
		return "[]string{}"
	}
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, strconv.Quote(value))
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func pyStringList(values []string) string {
	return "[" + strings.Join(quotedJSON(values), ", ") + "]"
}

func tsStringArray(values []string) string {
	return "[" + strings.Join(quotedJSON(values), ", ") + "]"
}

func quotedJSON(values []string) []string {
	out := make([]string, 0, len(values))
	for _, value := range values {
		out = append(out, jsonString(value))
	}
	return out
}

func jsonString(value string) string {
	raw, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return string(raw)
}
