// SPDX-License-Identifier: MIT
package main

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"

	"github.com/pcguest/custos/internal/receipt"
)

// TestE2EIngestAttestationAndDigestLookup is the custody end-to-end path a
// bundle takes once `atb intercept --custos` (or any pusher) submits it: the
// real custosd routes carry it from /ingest through to an independently
// verifiable attestation and the digest-keyed lookup. It drives newMux (the
// actual daemon routing) with a real ATB-produced fixture bundle rather than a
// hand-rolled mux or a synthetic receipt, so the wire contract is exercised
// exactly as a client sees it.
//
// The fixture is generated by scripts/generate_profile_fixtures.go (CI runs it
// before the custos module tests; the pre-commit hook regenerates it locally).
// If it is absent — e.g. a bare `go test ./...` without prior generation — the
// test skips rather than failing, so it never produces a spurious red.
func TestE2EIngestAttestationAndDigestLookup(t *testing.T) {
	const profileID = "atb.profile.privileged_tool_action"
	fixture := filepath.Join("..", "..", "..", "examples", "bundles", "profiles", "privileged_tool_action-pass.atb")
	bundleBytes, err := os.ReadFile(fixture) // #nosec G304 -- fixed test fixture path
	if err != nil {
		t.Skipf("profile fixture not generated (%v); run scripts/generate_profile_fixtures.go", err)
	}

	mux, _, _ := newSeededMux(t)

	// 1. Ingest the real bundle through the real /ingest route.
	ingestReq := httptest.NewRequest(http.MethodPost, "/ingest?profile_id="+profileID, bytes.NewReader(bundleBytes))
	ingestRec := httptest.NewRecorder()
	mux.ServeHTTP(ingestRec, ingestReq)
	if ingestRec.Code != http.StatusCreated {
		t.Fatalf("ingest status = %d, want 201 (body=%q)", ingestRec.Code, ingestRec.Body.String())
	}
	var rec receipt.Receipt
	if err := json.Unmarshal(ingestRec.Body.Bytes(), &rec); err != nil {
		t.Fatalf("decode receipt: %v", err)
	}
	if rec.ReceiptID == "" || rec.BundleHash == "" {
		t.Fatalf("receipt missing identifiers: %+v", rec)
	}
	if rec.Attestation == nil {
		t.Fatal("ingested receipt carries no attestation")
	}

	// 2. The attestation verifies server-side through the real route.
	attReq := httptest.NewRequest(http.MethodGet, "/receipts/"+rec.ReceiptID+"/attestation", nil)
	attRec := httptest.NewRecorder()
	mux.ServeHTTP(attRec, attReq)
	if attRec.Code != http.StatusOK {
		t.Fatalf("attestation status = %d, want 200 (body=%q)", attRec.Code, attRec.Body.String())
	}
	var att struct {
		ReceiptID  string `json:"receipt_id"`
		BundleHash string `json:"bundle_hash"`
		Valid      bool   `json:"valid"`
		Error      string `json:"error"`
	}
	if err := json.Unmarshal(attRec.Body.Bytes(), &att); err != nil {
		t.Fatalf("decode attestation: %v", err)
	}
	if !att.Valid {
		t.Fatalf("attestation not valid: %q", att.Error)
	}
	if att.ReceiptID != rec.ReceiptID || att.BundleHash != rec.BundleHash {
		t.Fatalf("attestation identifiers drift: att=%+v rec=%s/%s", att, rec.ReceiptID, rec.BundleHash)
	}

	// 3. The digest-keyed lookup finds the same receipt by its bundle hash.
	hashReq := httptest.NewRequest(http.MethodGet, "/receipts/by-hash?bundle_hash="+rec.BundleHash, nil)
	hashRec := httptest.NewRecorder()
	mux.ServeHTTP(hashRec, hashReq)
	if hashRec.Code != http.StatusOK {
		t.Fatalf("by-hash status = %d, want 200 (body=%q)", hashRec.Code, hashRec.Body.String())
	}
	var byHash struct {
		BundleHash string            `json:"bundle_hash"`
		Count      int               `json:"count"`
		Receipts   []receipt.Receipt `json:"receipts"`
	}
	if err := json.Unmarshal(hashRec.Body.Bytes(), &byHash); err != nil {
		t.Fatalf("decode by-hash: %v", err)
	}
	if byHash.Count < 1 {
		t.Fatalf("by-hash found no receipts for %s", rec.BundleHash)
	}
	found := false
	for _, r := range byHash.Receipts {
		if r.ReceiptID == rec.ReceiptID {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("by-hash did not return the ingested receipt %s", rec.ReceiptID)
	}

	// 4. The receipt is also fetchable by its content-addressed ID.
	getReq := httptest.NewRequest(http.MethodGet, "/receipts/"+rec.ReceiptID, nil)
	getRec := httptest.NewRecorder()
	mux.ServeHTTP(getRec, getReq)
	if getRec.Code != http.StatusOK {
		t.Fatalf("get receipt status = %d, want 200", getRec.Code)
	}
}
